### ISSUE TITLE
Either return only first sentence or "No JSON object could be decoded" Error when tranlate a long paragraph.

### ISSUE THREAD

**Issue by tdzhang** [ssut/py-googletrans#10]
Hi, the translate func returns either the first sentence or "No JSON object could be decoded" Error when I translate a long paragraph.

Should I tokenize the paragraph first? But that is hard to do when dealing with non-english src language.

Thanks!

**Comment by ssut** [comment]
I guess the problem is caused by the limit of a GET request because Google translate uses POST instead of GET for the API requests with large data. However, it would be helpful if you could attach full text so this can be investigated and rectified.
