### ISSUE TITLE
Is it possible to do transliteration? If yes, how?

### ISSUE THREAD

**Issue by elieobeid7** [ssut/py-googletrans#101]

**Comment by helloworldkr** [comment]
Have a look at this npm library for transliteration
https://www.npmjs.com/package/google-transliterate.

As far as this library is concerned
When it will not be able to find the meaning of word and perform a translation, this will transliteration

**Comment by elieobeid7** [comment]
Thank you, is there a python equivalent of the library you gave me?

**Comment by helloworldkr** [comment]
you can try this out 
https://pypi.org/project/transliterate/

**Comment by elieobeid7** [comment]
That one doesn't support Arabic, it's okay I'll use the nodejs one you gave me thanks so much.
