### ISSUE TITLE
HTTPSConnectionPool(host='translate.google.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fec11cf58d0>: Failed to establish a new connection: [Errno 110] Connection timed out',))

### ISSUE THREAD

**Issue by Mr-wang2016** [ssut/py-googletrans#104]
Hi，when i run 

from googletrans import Translator
translator = Translator()
print(translator.translate('今天天气不错').text)

in ipython, i got a error 'HTTPSConnectionPool(host='translate.google.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fec11cf58d0>: Failed to establish a new connection: [Errno 110] Connection timed out',))'
Can someone know the reason?thanks a lot!

**Comment by DipenChawla** [comment]
Were you able to solve this?
