### ISSUE TITLE
AttributeError: 'int' object has no attribute 'lower'

### ISSUE THREAD

**Issue by ascpixel** [ssut/py-googletrans#111]
I get this error when I execute my program:
https://pastebin.com/YPKad8zp

This caused the error: `currentText = maing.translate(currentText, dest=lang, src="auto")`
Lang and currentText are variables: 'pl' and 'This is an test!' respectively.

I'm pretty sure that's a bug, but maybe I've done something wrong? I've taken Python previous year sooo.... yeah....

**Comment by s4magier** [comment]
Are you sure lang is = pl? try: dest = 'pl' and src = 'en'
