### ISSUE TITLE
error about json when execute simple translation

### ISSUE THREAD

**Issue by pandbsoftware** [ssut/py-googletrans#116]
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/googletrans/client.py", line 172, in translate
    data = self._translate(text, dest, src)
  File "/usr/lib/python2.7/site-packages/googletrans/client.py", line 81, in _translate
    data = utils.format_json(r.text)
  File "/usr/lib/python2.7/site-packages/googletrans/utils.py", line 62, in format_json
    converted = legacy_format_json(original)
  File "/usr/lib/python2.7/site-packages/googletrans/utils.py", line 54, in legacy_format_json
    converted = json.loads(text)
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by DianaDI** [comment]
from googletrans import Translator
translator = Translator()
translator.translate('안녕하세요.')

---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
<ipython-input-19-35677b77249a> in <module>()
      1 from googletrans import Translator
      2 translator = Translator()
----> 3 translator.translate('안녕하세요.')

C:\ProgramData\Anaconda3\lib\site-packages\googletrans\client.py in translate(self, text, dest, src)
    170 
    171         origin = text
--> 172         data = self._translate(text, dest, src)
    173 
    174         # this code will be updated when the format is changed.

C:\ProgramData\Anaconda3\lib\site-packages\googletrans\client.py in _translate(self, text, dest, src)
     79         r = self.session.get(url, params=params)
     80 
---> 81         data = utils.format_json(r.text)
     82         return data
     83 

C:\ProgramData\Anaconda3\lib\site-packages\googletrans\utils.py in format_json(original)
     60         converted = json.loads(original)
     61     except ValueError:
---> 62         converted = legacy_format_json(original)
     63 
     64     return converted

C:\ProgramData\Anaconda3\lib\site-packages\googletrans\utils.py in legacy_format_json(original)
     52             text = text[:p] + states[j][1] + text[nxt:]
     53 
---> 54     converted = json.loads(text)
     55     return converted
     56 

C:\ProgramData\Anaconda3\lib\json\__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    352             parse_int is None and parse_float is None and
    353             parse_constant is None and object_pairs_hook is None and not kw):
--> 354         return _default_decoder.decode(s)
    355     if cls is None:
    356         cls = JSONDecoder

C:\ProgramData\Anaconda3\lib\json\decoder.py in decode(self, s, _w)
    337 
    338         """
--> 339         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    340         end = _w(s, end).end()
    341         if end != len(s):

C:\ProgramData\Anaconda3\lib\json\decoder.py in raw_decode(self, s, idx)
    355             obj, end = self.scan_once(s, idx)
    356         except StopIteration as err:
--> 357             raise JSONDecodeError("Expecting value", s, err.value) from None
    358         return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by DianaDI** [comment]
from googletrans import Translator
translator = Translator()
translator.translate('안녕하세요.')

JSONDecodeError Traceback (most recent call last)
in ()
1 from googletrans import Translator
2 translator = Translator()
----> 3 translator.translate('안녕하세요.')

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by mydockergit** [comment]
Same here with python 3.7:
```
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:06:47) [MSC v.1914 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from googletrans import Translator
>>> translator = Translator()
>>> translator.translate('номер')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\myuser\AppData\Local\Programs\Python\Python37-32\lib\site-packages\googletrans\client.py", line 172, in translate
    data = self._translate(text, dest, src)
  File "C:\Users\myuser\AppData\Local\Programs\Python\Python37-32\lib\site-packages\googletrans\client.py", line 81, in _translate
    data = utils.format_json(r.text)
  File "C:\Users\myuser\AppData\Local\Programs\Python\Python37-32\lib\site-packages\googletrans\utils.py", line 62, in format_json
    converted = legacy_format_json(original)
  File "C:\Users\myuser\AppData\Local\Programs\Python\Python37-32\lib\site-packages\googletrans\utils.py", line 54, in legacy_format_json
    converted = json.loads(text)
  File "C:\Users\myuser\AppData\Local\Programs\Python\Python37-32\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\myuser\AppData\Local\Programs\Python\Python37-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\myuser\AppData\Local\Programs\Python\Python37-32\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

It worked 2 hours ago and then suddenly it stopped working.

**Comment by mydockergit** [comment]
I think the problem is because of sending too much traffic.
I debugged it and saw that it failed on utils.py at line 54:
https://github.com/ssut/py-googletrans/blob/4aebfb18faa45a7d7817fbd4b8fe8ff502bf9e81/googletrans/utils.py#L54

The error from google:  

> Our systems have detected unusual traffic from your computer network. Please try your request again later.

**Comment by masterchop** [comment]
So this is a big problem, do we know how much can we use this? what is the limit?
it cant be reliable if we are getting blocked.

**Comment by berkayberkman** [comment]
any idea how to fix this? or anyone know another library working on python3.6+?

**Comment by jitunair18** [comment]
I am facing this same issue. Json error out of the blue when the exact same thing was working many times over before

**Comment by masterchop** [comment]
you need a new IP in order to be able to use it. my isp allow to ip swap pretty easily so no problem for me. But you will have to pay if you cant do that.
