### ISSUE TITLE
[Error] python 3.4 compatibility

### ISSUE THREAD

**Issue by kaizen36** [ssut/py-googletrans#120]
The version for the requests package is not specified (https://github.com/ssut/py-googletrans/blob/master/setup.py#L63) and as of May 16 2019 the new release (requests==2.22.0) dropped support for python 3.4. 

```
Collecting requests (from googletrans)
  Downloading [xxxxxxx]/requests-2.22.0-py2.py3-none-any.whl (57kB)
requests requires Python '>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*'
```

Please fix requests==2.21.0 (or announce that you won't support 3.4!). 

Thanks!

**Comment by Djailla** [comment]
No more support of py34

**Comment by Djailla** [comment]
@0mars you can close this issue

**Comment by ssut** [comment]
He hasn't accepted the invitation yet so I am going to close this issue instead. It's okay to mention both him and me anyway. Thanks @Djailla.
