### ISSUE TITLE
Too many requests 429. JSONDecodeError

### ISSUE THREAD

**Issue by IdeoG** [ssut/py-googletrans#121]
Today i found unexpected exception from googletrans library - the JSONDecodeError.

So. i figured out and found logs from the library:
```
------------------------------ Captured log call ------------------------------
DEBUG    urllib3.connectionpool:connectionpool.py:813 Starting new HTTPS connection (1): translate.google.com:443
DEBUG    urllib3.connectionpool:connectionpool.py:393 https://translate.google.com:443 "GET / HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:393 https://translate.google.com:443 "GET /translate_a/single?client=t&sl=auto&tl=en&hl=en&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&ie=UTF-8&oe=UTF-8&otf=1&ssel=0&tsel=0&tk=487977.125191&q=TOWER HTTP/1.1" 429 2264
========================== 1 failed in 0.90 seconds ===========================
```

Be careful, google translate applies usage restrictions. It isn't unlimited as it's said in `README.md`.

P.S.: I made 100 requests in a row and i was blocked.

**Comment by masterchop** [comment]
I guess i got blocked too :( not good :(

**Comment by ssut** [comment]
This library relies on web version of google translate which may violate the term of google translator. Google keeps pushing us to use their official translate API that needs billing, and sadly, I would highly recommend to use that to anyone struggling with stability issues using this library. However, I will give it a try to deal with this long-lived issue when I have a free moment.

**Comment by masterchop** [comment]
Thanks for trying :)
