### ISSUE TITLE
The service is not available now?

### ISSUE THREAD

**Issue by zhaopeinan** [ssut/py-googletrans#123]
I tried several times today, it keeps returning timeout. Any body got the same problem?

**Comment by BarbaraGrape** [comment]
I have the same problem. Hope that somebody know the way how it is possibly can be solved (but guess it is highly unlikely).

**Comment by onlyredrain2003** [comment]
same prob now , not sure if this can be fixed by changing the src url ? any idea pls

**Comment by Darkblader24** [comment]
I just tried it and it works fine for me

**Comment by onlyredrain2003** [comment]
thanks @Darkblader24 , seems its url issue , could u pls help to using src url for a try , and share the one you were using , such as : translator = Translator(service_urls='translate.google.com')

**Comment by onlyredrain2003** [comment]
oh ! i found that fixed by using 
translator = Translator(service_urls=['translate.google.cn',])
can't miss that comma !
