### ISSUE TITLE
how to get text from  Translated(src=en, dest=hi, text=वह एक अच्छा आदमी है।, pronunciation=None, extra_data="{'translat...")

### ISSUE THREAD

**Issue by GyanPrakashSinghIIITG** [ssut/py-googletrans#125]

**Comment by Fatty69420** [comment]
from googletrans import Translator
translator = Translator()
Translation = ((translator.translate('वह एक अच्छा आदमी है।', dest='en')).text)
print(Translation)

**Comment by GyanPrakashSinghIIITG** [comment]
I wanted to extract Hindi text part only from Translated(....).
I hope now you get my question.

**Comment by Fatty69420** [comment]
just add .text after the variable name then
