### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by huangxininchina** [ssut/py-googletrans#128]
![image](https://user-images.githubusercontent.com/50193036/61199246-cdc37e80-a70f-11e9-8044-5cc2b4d07d28.png)
hi

I tried to use the Googletrans, but it fails to connect to the server,  I don't understand why

I'm in China, I have used API, I can visit google websites

Anyone can help me?

**Comment by larryisthere** [comment]
GFWed

**Comment by rainsword** [comment]
You may use translate.google.cn for translate.
But if you use translate.google.com, perhaps you are using proxy, so you must set proxies.
