### ISSUE TITLE
Translate text inside html

### ISSUE THREAD

**Issue by sam-thecoder** [ssut/py-googletrans#129]
This is a great tool, I've got a case where implementing this on a site the text might be embeded inside of html.
I'm not sure if you can make it work with this.

**Comment by dimuska139** [comment]
@sam-thecoder you can grab text from html using [beautifulsoup4](https://pypi.org/project/beautifulsoup4/) and translate it via py-googletrans. Html parsing is a task not for translation library i suppose.

**Comment by vesper8** [comment]
extracting the text from html is very easy.. the hard part is if you want to conserve the html, re-inserting the text back into the html post-translation is quite tricky it seems.. if anyone knows of a library or script that can assist with this I'd love to know about it

**Comment by dimuska139** [comment]
> extracting the text from html is very easy.. the hard part is if you want to conserve the html, re-inserting the text back into the html post-translation is quite tricky it seems.. if anyone knows of a library or script that can assist with this I'd love to know about it

I suppose you should not extract the text from html and re-inserting the text back into the html. Try to translate the text before inserting it in html template. For example:

```python
from googletrans import Translator
from jinja2 import Template

t = Template("<h1>Hello {{ name }}!</h1>")
translator = Translator()
print(t.render(name=translator.translate('Алексей', dest='en')))
```

If you want to extract the text from html, translate it and re-inserting the text back try to use beautifulsoup4:

```python
from bs4 import BeautifulSoup
from googletrans import Translator

html = """<h1 data-trans>Привет, Петя!</h1>
<img src="/profile.jpg/>
<p data-trans>Как настроение?</p>
"""

translator = Translator()
soup = BeautifulSoup(html, 'html.parser')
tags = soup.select('[data-trans]')
for tag in tags:
    tag.string = translator.translate(tag.text, dest='en'))

print(soup.prettify())
```
P.s. sorry for my bad english

**Comment by vesper8** [comment]
@dimuska139 thanks a lot for taking the time to write that. I am dealing with content that is already placed within html. I really like your 2nd example of adding a `data-trans` attribute to all the tags you wish to translate and then using that to bulk translate.

I guess the only problem I can see with this is when you have nested html elements that you wish to translate. For example

```
<p>The rabbit went for a swim in <em>the river</em> and was never seen again</p>
```

Do you have any idea how I might be able to conserve the `em` tag in this case?

Currently if I try to pass the whole string within the `p` tag, googletrans does some weird things with the `em` tags

**Comment by dimuska139** [comment]
@vesper8 I think py-googletrans not supports html tags in text. You should remove them from the string before passing to `translate` method. So there is no way to find the piece of translated string to wrap it with `<em>` as it was in the original phrase.

**Comment by milahu** [comment]
> the hard part is if you want to conserve the html, re-inserting the text back into the html post-translation is quite tricky it seems.. if anyone knows of a library or script that can assist with this I'd love to know about it

solved in https://github.com/ssut/py-googletrans/issues/99#issuecomment-848714972
