### ISSUE TITLE
encoding or decoding problem?

### ISSUE THREAD

**Issue by wotanzheng** [ssut/py-googletrans#13]
If there was a sepecial char, such as copyright symbol (© )，the program gets an error.
No JSON object could be decoded

**Comment by ssut** [comment]
I'm investigating this issue and I will fix this soon.

**Comment by wotanzheng** [comment]
Thank you so much. If it's convient, is there any chance to develop a feature to read source text from TXT file and write translation text to another TXT? The simplest one is OK.

**Comment by ssut** [comment]
I think it's out of scope for googletrans, but I will consider implementing it.

**Comment by ssut** [comment]
I fixed this issue with the commit above. Please try upgrading to googletrans 2.1.1 where this issue is fixed.

**Comment by wotanzheng** [comment]
Thank you so much.
