### ISSUE TITLE
Google cloud api

### ISSUE THREAD

**Issue by MayuraVerma** [ssut/py-googletrans#131]
I have signed up for the google cloud api.

I have saved the JSON in environment.

I want use this API with IP being block. I don't mind getting charged for the translation from google.

Is there anything I need to do to link the JSON to this script?

**Comment by PhilippeTrounev** [comment]
You would need to use the actual google cloud library for that. 
https://pypi.org/project/google-cloud-translate/

This is the free version, but you are risking of being blocked if you are using the same ip, translating GB's of data, etc.
