### ISSUE TITLE
JSONDecodeError: Expecting value

### ISSUE THREAD

**Issue by ashishshankar0894** [ssut/py-googletrans#135]
Getting this error recently. 

  File "#path\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None

JSONDecodeError: Expecting value

**Comment by xronsx** [comment]
I have the same issue... Any solution?

**Comment by sSimuSs** [comment]
Is there any solution?

**Comment by topnax** [comment]
Same issue :(

**Comment by ashankar-RMS** [comment]
I guess the error occurs when we exceed the daily click limit.
Next day it resets. .
Did it reset in the next day for anyone?

**Comment by ashishshankar0894** [comment]
I think the error occurs when we exceed the daily click limit.
Next day it resets.
Did it reset in the next day for anyone?

**Comment by sSimuSs** [comment]
> I think the error occurs when we exceed the daily click limit.
> Next day it resets.
> Did it reset in the next day for anyone?

Yes, it turns out there is a limit of requests per day.

**Comment by topnax** [comment]
This happens to me when I send HTML for translation.

**Comment by sSimuSs** [comment]
https://cloud.google.com/translate/quotas
