### ISSUE TITLE
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by privileged8222** [ssut/py-googletrans#144]
`Ignoring exception in command beanify:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "beanbot.py", line 52, in beanify
    await ctx.send(bean(str(sentence), random.randint(6,15)))
  File "beanbot.py", line 33, in bean
    phrase = translate(phrase,langs[lang])
  File "beanbot.py", line 29, in translate
    return translator.translate(words,dest=lang).text
  File "/usr/local/lib/python3.6/dist-packages/googletrans/client.py", line 172, in translate
    data = self._translate(text, dest, src)
  File "/usr/local/lib/python3.6/dist-packages/googletrans/client.py", line 81, in _translate
    data = utils.format_json(r.text)
  File "/usr/local/lib/python3.6/dist-packages/googletrans/utils.py", line 62, in format_json
    converted = legacy_format_json(original)
  File "/usr/local/lib/python3.6/dist-packages/googletrans/utils.py", line 54, in legacy_format_json
    converted = json.loads(text)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/bot.py", line 863, in invoke
    await ctx.command.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 728, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 88, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`
get this every time i run this program:

`translator = Translator()
langs = ['ar','sq','ar','ga','it','ja','ms','eu','bn','be','bg','ca','la','kn','ko','mk']

def translate(words,lang):
    return translator.translate(words,dest=lang).text

def bean(phrase,num): # max num is 15
    for lang in range(num):
        phrase = translate(phrase,langs[lang])
        phrase = translate(phrase,"en")
        #print(phrase)
    return phrase`

**Comment by packofbones** [comment]
Works for me, although do note that there may be 2 causes which I've noticed when encountering this issue:
1) Exceeding the daily API limit (your IP getting banned), which you can circumvent by using proxies (you can set proxies when initialising `Translator()`, as shown [here](https://github.com/ssut/py-googletrans/blob/master/googletrans/client.py#L33)))
2) Sending emojis in text, which I fix by using [demoji](https://pypi.org/project/demoji/)

**Comment by RankoR** [comment]
@packofbones do you know the daily limit per IP?

**Comment by mirusu400** [comment]
@RankoR [This article](https://support.arcadier.com/hc/en-us/articles/115001371134-Translating-your-marketplace-using-Google-API-) said that Google Translate API has `2 million characters per day` and `100,000 characters per 100 second` limit.

**Comment by perskes** [comment]
@RankoR 

I second that, it says the API is unlimited in the docs, but that's not true.

I found this code in an old project I did (and I am re-writing now):

`    try:
        trans = translator.translate(str(word), dest=dstLang, src=srcLang)
    except ValueError:
        print("Hit an exception, trying again in 100.")
        time.sleep(100)  # google limits 100k characters per 100s
`

This seems to be old news (and frankly, I understand, but it was much better back then).

I literaly ran above code once on a 2-character word ("Oi", portuguese to english) and I got hit with the exception you posted above.

Tried the same code on repl.it (just in case my IDE or network is at fault) and it works, thus my IP seems to be blocked. 30 more minutes till midnight here, to see if it sets back the ban..

**Comment by agombert** [comment]
@perskes I just have experienced the same, I have changed my VPN location but it looks like it can detect it. I used my mobil connection to get more translations, but after a few it happens again...

**Comment by skanalytic** [comment]
I also hit this due to API limits. I think they should at least improve the error messaging here to make this clearer. 

"JSONDecodeError: Expecting value: line 1 column 1 (char 0)" (or anything in the callback trace) is not descriptive of the issue. It should be "LimitError: API Limit of <rate_limit> hit" or something.

**Comment by privileged8222** [comment]
> I also hit this due to API limits. I think they should at least improve the error messaging here to make this clearer.
> 
> "JSONDecodeError: Expecting value: line 1 column 1 (char 0)" (or anything in the callback trace) is not descriptive of the issue. It should be "LimitError: API Limit of <rate_limit> hit" or something.

I havent really been watching this thread for a while so ive actually forgotten to post the 'fix' (thanks for reminding me).
As said above it seems to be API limits, my program didnt take advantage of any proxies so it was about 13 people using this program constantly translating quite long sentences. The ban seems to go away after a few days, so i just had to add a cooldown!
