### ISSUE TITLE
try/except on translate()

### ISSUE THREAD

**Issue by x0rzkov** [ssut/py-googletrans#145]
Hi,

Hope you are all well !

I would like to try/except the translate function.
https://github.com/twintproject/twint/blob/7cde07f619c63d8044e0c5872a2b03f331394790/twint/tweet.py#L116-L123

```
    if config.Translate == True:
        try:
            # config.Translate
            ts = translator.translate(text=t.tweet, dest=config.TranslateDest)
            t.translate = str(ts.text)
            t.trans_src = str(ts.src)
            t.trans_dest = str(ts.dest)
        except KeyError:
            logme.debug(__name__+':Tweet:translator.translate')
```

What is the best way to do it ? what should I use instead of **KeyError** ?

Cheers,
X

**Comment by sheiun** [comment]
@x0rzkov 

If you want to catch the error when given invalid `dest` argument, you should use `ValueError`.
