### ISSUE TITLE
Ability to specify model of googletranslation

### ISSUE THREAD

**Issue by murtazasamiwala** [ssut/py-googletrans#146]
Hello Ssut,

Thanks for sharing this library. Through some digging, I realized that your model outputs translation according to the base model of google translate. Is it possible to change this to the nmt model.

Thanks

**Comment by louwers** [comment]
I think this library is a hack to get the output from the free Google Translate service, not an interface to Google's (paid) Translation API.

**Comment by flriancu** [comment]
There are three translation models, all of which will return different translations:

- `client=te` (or `client=te_lib&sp=pbmt`) is the PBMT model
- `client=te_lib` (optionally with `sp=nmt`) is the superior NMT model
- `client=webapp` is a third model, I cannot say which one for sure, but seemingly not as good as NMT.

For example, from `ja` to `en`:

`くるしいことばかり本物で しあわせなことはぜんぶ夢だったらどうしよう`

- `client=te`: `Painful it just be real in a happiness What if was a dream everything`
- `client=te_lib` (best fit): `What if all the hard things are real and happiness is a dream`
- `client=webapp`: `What if all the hard things are genuine and happy`

**Comment by flriancu** [comment]
imo, per above, it would be a very nice improvement if we could specify the translation model.

**Comment by kangbrilliant** [comment]
@flriancu 
hi，have you found a solution to solve this problem？

**Comment by flriancu** [comment]
@kangbrilliant it seems that the option `client=te_lib` now gives the same results as `client=webapp`, so I suspect that the changes in former eventually end up in the latter.

If you go to https://translate.google.com, you will get the following results:

- `くるしいことばかり本物で しあわせなことはぜんぶ夢だったらどうしよう` -> `What if all the hard things are genuine and happy`
- with a slash at the end: `くるしいことばかり本物で しあわせなことはぜんぶ夢だったらどうしよう/` -> `What if all the hard things are real and happy are all dreams /`
- best translation, with a backslash at the end: `くるしいことばかり本物で しあわせなことはぜんぶ夢だったらどうしよう\` -> `What if all the hard things are real and happiness is a dream \`

This behavior, where random characters influence the translated result, is very old and I'm absolutely sure that the results will keep changing over time, for better or for worse; it's in the nature of the machine learning process. What the `py-googletrans` developer(s) can do is supply an array of translations, where the original text was suffixed with some signs at the end, as I did above.

**Comment by AlexandraDrobut** [comment]
Hello! Google translator has 2 models used by the translator server as presented in this documentation part: https://cloud.google.com/translate/docs/basic/translating-text#translating_text. It seems like by default library clients make the request to the base= PBMT model whose translation results are very week compared to the nmt model.
If you want to use the nmt model  you have to create a google account and use some account credentials for the requests.

export GOOGLE_APPLICATION_CREDENTIALS="" set environment credentials
from google.cloud import translate_v2 as translate
translate_client = translate.Client()
result = translate_client.translate(text, target_language='ro', model="nmt")

and you' ll be able to have your translations very accurate!

**Comment by flriancu** [comment]
@AlexandraDrobut from my testing of the Translate API, I have found that the web application yields the same results as the NMT model (called via their API). I tested this at the time of my first comment, some months ago. Do you get different results?
