### ISSUE TITLE
the result get from this lib is not the same with the result get from google translate website

### ISSUE THREAD

**Issue by THMAIL** [ssut/py-googletrans#149]
such as ,the company "拼多多", 
for google translate website, the result is "PinDuoduo", that's right;
but for this lib, the result is "A lot of fight";

this is just a example,you can try other sentences, many results are not the same with offical

**Comment by THMAIL** [comment]
Can someone tell me why?

**Comment by H0bby** [comment]
这个库只是接口调用，内容源自于谷歌。对于非术语词汇谷歌的翻译接口并不是每次都会返回一样的翻译结果。

This library is just an interface call and the content originates from Google. Google's translation interface for non-term words does not always return the same translation results.

**Comment by hjnnjh** [comment]
I have the same problem, who can tell me how to solve this problem?
