### ISSUE TITLE
PyPI package is not updated

### ISSUE THREAD

**Issue by kikones34** [ssut/py-googletrans#152]
Commit https://github.com/ssut/py-googletrans/commit/4aebfb18faa45a7d7817fbd4b8fe8ff502bf9e81 fixed an important issue and bumped the version to 2.4.1.
In PyPI, the issue is not fixed and the version is 2.4.0.

**Comment by mzeidhassan** [comment]
If you want to install the latest version from github, use this command:

`pip install git+https://github.com/ssut/py-googletrans.git`

![image](https://user-images.githubusercontent.com/7589948/77236885-44125d80-6b88-11ea-979a-b4d71cbb7e43.png)
