### ISSUE TITLE
Feature request: incorporating requests_cache

### ISSUE THREAD

**Issue by yucongo** [ssut/py-googletrans#16]
Very nice thanks! Hope it lasts...:)

I wonder if you can incorperate request_cache in googletrans.

The use of requests_cache may reduce the possibility of an IP being blocked. For simple use, just add these two lines after import requests in client.py:

import requests_cache
requests_cache.install_cache('googletrans_cache')

I tested in Python 3.4, it works great. I am not proficient enough to suggest any more sophisticated use of request_cache though.

**Comment by ssut** [comment]
Thanks for your thoughtful proposal. I will consider this.

**Comment by yucongo** [comment]
I added requests_cache and a few lines to your client.py for my own use. Feel free to make use of anything you like. translate(self, text, dest='en', src='auto') is changed to  translate(self, text, dest='en', src='auto', delay=None), to introduce a random delay if delay is set and if requests' response is not from the cache. 

Great project, very useful to me. It would be a shame if google changes things.

# -*- coding: utf-8 -*-
"""
A Translation module.

You can translate text using this module.
"""
from time import sleep
from random import random
import logging
import requests

from googletrans import urls, utils
from googletrans.compat import PY3
from googletrans.gtoken import TokenAcquirer
from googletrans.constants import DEFAULT_USER_AGENT, LANGUAGES, SPECIAL_CASES
from googletrans.models import Translated, Detected

import requests_cache

# cache file set to googletrans_cache.sqlite if not already set in previous import requests_cache  # noqa
requests_cache.install_cache('googletrans_cache')

LOGGER = logging.getLogger(__name__)
LOGGER.addHandler(logging.NullHandler())

EXCLUDES = ('en', 'ca', 'fr')


class Translator(object):
    """Google Translate ajax API implementation class

    You have to create an instance of Translator to use this API

    :param service_urls: google translate url list. URLs will be used randomly.
                         For example ``['translate.google.com', 'translate.google.co.kr']``
    :type service_urls: a sequence of strings

    :param user_agent: the User-Agent header to send when making requests.
    :type user_agent: :class:`str`
    """

    def __init__(self, service_urls=None, user_agent=DEFAULT_USER_AGENT):
        self.session = requests.Session()
        self.session.headers.update({
            'User-Agent': user_agent,
        })
        self.token_acquirer = TokenAcquirer(session=self.session)
        # self.service_urls = service_urls or ['translate.google.com']
        self.service_urls = service_urls or ['translate.google.cn']

        self.from_cache = False

        # Use HTTP2 Adapter if hyper is installed
        try:  # pragma: nocover
            from hyper.contrib import HTTP20Adapter
            self.session.mount(urls.BASE, HTTP20Adapter())
        except ImportError:  # pragma: nocover
            pass

    def _pick_service_url(self):
        if len(self.service_urls) == 1:
            return self.service_urls[0]
        return random.choice(self.service_urls)

    def _translate(self, text, dest='en', src='auto'):
        if src != 'auto':
            if src not in LANGUAGES.keys() and src in SPECIAL_CASES.keys():
                src = SPECIAL_CASES[src]
            elif src not in LANGUAGES.keys():
                raise ValueError('invalid source language')

        if dest not in LANGUAGES.keys():
            if dest in SPECIAL_CASES.keys():
                dest = SPECIAL_CASES[dest]
            else:
                raise ValueError('invalid destination language')

        if not PY3 and isinstance(text, str):  # pragma: nocover
            text = text.decode('utf-8')

        token = self.token_acquirer.do(text)
        params = utils.build_params(query=text, src=src, dest=dest,
                                    token=token)
        url = urls.TRANSLATE.format(host=self._pick_service_url())
        r = self.session.get(url, params=params)

        self.from_cache = r.from_cache
        LOGGER.debug(" from_cache: %s", self.from_cache)

        data = utils.format_json(r.text)
        return data

    def translate(self, text, dest='en', src='auto', delay=None):
        """Translate text from source language to destination language

        :param text: The source text(s) to be translated. Batch translation is supported via sequence input.
        :type text: UTF-8 :class:`str`; :class:`unicode`; string sequence (list, tuple, iterator, generator)

        :param dest: The language to translate the source text into.
                     The value should be one of the language codes listed in :const:`googletrans.LANGUAGES`.
        :param dest: :class:`str`; :class:`unicode`

        :param src: The language of the source text.
                    The value should be one of the language codes listed in :const:`googletrans.LANGUAGES`.
                    If a language is not specified,
                    the system will attempt to identify the source language automatically.
        :param src: :class:`str`; :class:`unicode`

        :rtype: Translated
        :rtype: :class:`list` (when a list is passed)

        Basic usage:
            >>> from googletrans import Translator
            >>> translator = Translator()
            >>> translator.translate('안녕하세요.')
            <Translated src=ko dest=en text=Good evening. pronunciation=Good evening.>
            >>> translator.translate('안녕하세요.', dest='ja')
            <Translated src=ko dest=ja text=こんにちは。 pronunciation=Kon'nichiwa.>
            >>> translator.translate('veritas lux mea', src='la')
            <Translated src=la dest=en text=The truth is my light pronunciation=The truth is my light>

        Advanced usage:
            >>> translations = translator.translate(['The quick brown fox', 'jumps over', 'the lazy dog'], dest='ko')
            >>> for translation in translations:
            ...    print(translation.origin, ' -> ', translation.text)
            The quick brown fox  ->  빠른 갈색 여우
            jumps over  ->  이상 점프
            the lazy dog  ->  게으른 개
        """
        if delay:
            if isinstance(delay, (int, float)):
                delay = min(0.5, delay)
            else:
                delay = 0.5

        if isinstance(text, list):
            result = []
            for item in text:
                translated = self.translate(item, dest=dest, src=src)
                result.append(translated)
                if not self.from_cache and delay:  # if delay is set, sleep random secs (mean=delay) if response is not from cache  # noqa
                    sleep_time = delay - 0.5 + random()
                    LOGGER.debug(" sleep %.2f sec", sleep_time)
                    sleep(sleep_time)
            return result

        origin = text
        data = self._translate(text, dest, src)

        # this code will be updated when the format is changed.
        translated = ''.join([d[0] if d[0] else '' for d in data[0]])

        # actual source language that will be recognized by Google Translator when the
        # src passed is equal to auto.
        try:
            src = data[-1][0][0]
        except Exception:  # pragma: nocover
            pass

        pron = origin
        try:
            pron = data[0][1][-1]
        except Exception:  # pragma: nocover
            pass
        if not PY3 and isinstance(pron, unicode) and isinstance(origin, str):  # pragma: nocover
            origin = origin.decode('utf-8')
        if dest in EXCLUDES and pron == origin:
            pron = translated

        # for python 2.x compatbillity
        if not PY3:  # pragma: nocover
            if isinstance(src, str):
                src = src.decode('utf-8')
            if isinstance(dest, str):
                dest = dest.decode('utf-8')
            if isinstance(translated, str):
                translated = translated.decode('utf-8')

        # put final values into a new Translated object
        result = Translated(src=src, dest=dest, origin=origin,
                            text=translated, pronunciation=pron)

        return result

    def detect(self, text):
        """Detect language of the input text

        :param text: The source text(s) whose language you want to identify.
                     Batch detection is supported via sequence input.
        :type text: UTF-8 :class:`str`; :class:`unicode`; string sequence (list, tuple, iterator, generator)

        :rtype: Detected
        :rtype: :class:`list` (when a list is passed)

        Basic usage:
            >>> from googletrans import Translator
            >>> translator = Translator()
            >>> translator.detect('이 문장은 한글로 쓰여졌습니다.')
            <Detected lang=ko confidence=0.27041003>
            >>> translator.detect('この文章は日本語で書かれました。')
            <Detected lang=ja confidence=0.64889508>
            >>> translator.detect('This sentence is written in English.')
            <Detected lang=en confidence=0.22348526>
            >>> translator.detect('Tiu frazo estas skribita en Esperanto.')
            <Detected lang=eo confidence=0.10538048>

        Advanced usage:
            >>> langs = translator.detect(['한국어', '日本語', 'English', 'le français'])
            >>> for lang in langs:
            ...    print(lang.lang, lang.confidence)
            ko 1
            ja 0.92929292
            en 0.96954316
            fr 0.043500196
        """
        if isinstance(text, list):
            result = []
            for item in text:
                lang = self.detect(item)
                result.append(lang)
            return result

        data = self._translate(text, dest='en', src='auto')

        # actual source language that will be recognized by Google Translator when the
        # src passed is equal to auto.
        src = ''
        confidence = 0.0
        try:
            src = ''.join(data[8][0])
            confidence = data[8][-2][0]
        except Exception:  # pragma: nocover
            pass
        result = Detected(lang=src, confidence=confidence)

        return result

**Comment by yucongo** [comment]
requests_cache doesnt seem to like hyper. With hyper installed, it results in the following exception. After pip uninstall hyper, trans_clipboard.py runs OK.

'''# trans_clipboard.py'''
trans_clipboard.py
import pyperclip
from googletrans import Translator
translator = Translator()
dest = 'zh-CN'
pyperclip.copy(translator.translate(text = pyperclip.paste(), dest=dest).text)

python trans_clipboard.py

Traceback (most recent call last):
  File "trans_clipboard.py", line 5, in <module>
    pyperclip.copy(translator.translate(text = pyperclip.paste(), dest=dest).text)
  File "D:\Python34\lib\site-packages\googletrans\client.py", line 149, in translate
    data = self._translate(text, dest, src)
  File "D:\Python34\lib\site-packages\googletrans\client.py", line 82, in _translate
    token = self.token_acquirer.do(text)
  File "D:\Python34\lib\site-packages\googletrans\gtoken.py", line 179, in do
    self._update()
  File "D:\Python34\lib\site-packages\googletrans\gtoken.py", line 56, in _update
    r = self.session.get('https://translate.google.com')
  File "D:\Python34\lib\site-packages\requests\sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "D:\Python34\lib\site-packages\requests_cache\core.py", line 126, in request
    **kwargs
  File "D:\Python34\lib\site-packages\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Python34\lib\site-packages\requests_cache\core.py", line 99, in send
    return send_request_and_cache_response()
  File "D:\Python34\lib\site-packages\requests_cache\core.py", line 93, in send_request_and_cache_response
    self.cache.save_response(cache_key, response)
  File "D:\Python34\lib\site-packages\requests_cache\backends\base.py", line 46, in save_response
    self.responses[key] = self.reduce_response(response), datetime.utcnow()
  File "D:\Python34\lib\site-packages\requests_cache\backends\storage\dbdict.py", line 160, in __setitem__
    sqlite.Binary(pickle.dumps(item)))
_pickle.PicklingError: Can't pickle <class 'hyper.contrib.HTTP20Adapter.build_response.<locals>.FakeOriginalResponse'>: attribute lookup FakeOriginalResponse on hyper.contrib failed
