### ISSUE TITLE
2.4.1 on pypi?

### ISSUE THREAD

**Issue by Andrej730** [ssut/py-googletrans#166]
Any information about when 2.4.1 will roll out to pypi? 

With 2.4.0 I receive the classic "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)" exception. What helped me is to change client parameter in request from 't' to either 'gtx' or 'webapp'- which basically is done in #102

Same issue as #152

**Comment by ssut** [comment]
I am closing this issue in favor of #150.
