### ISSUE TITLE
Some sentences can not be translated correctly.

### ISSUE THREAD

**Issue by wotanzheng** [ssut/py-googletrans#17]
I found that some sentences that special chars or number or english words connected with CCJK chars can not be translated correctly. The program will return the source text directly, not the target.  The following is some examples. You can test them:

Source:

⑥公司收到付款信息后将注册码发送至消费者邮箱；
1来源：http://www.199it.com/archives/xxxxx.html。
Wondershare Vivideo 软件
IN 部门

Enlish results from Google Translate Web:

⑥ company received payment information after the registration code sent to the consumer mailbox;
1 Source: http: //www.199it.com/archives/xxxxx.html.
Wondershare Vivideo software
IN department

**Comment by ssut** [comment]
it seems like google translate detects it as english text when special characters are present. could you try again with `src="zh-CN"`?

**Comment by wotanzheng** [comment]
Thank you so much. It works!
