### ISSUE TITLE
json.decoder.JSONDecodeError json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by saurabhkumarsaurabhkumar** [ssut/py-googletrans#172]
def upload_file():
    if request.method == 'POST':
        f = request.files['file']
        path='static/data/'+f.filename
        f.save(path)

        j_file = open('final-project-test.json', errors='ignore')
        loaded_json_model = j_file.read()
        j_file.close()

        model = model_from_json(loaded_json_model)
        model.load_weights('final-project-test.h5')
        img1 = image.load_img(f, target_size=(224,224))
        img1 = np.array(img1)
        img1 = img1.reshape((1,224,224,3))
        img1 = img1/255
        prediction = model.predict(img1)
        pred = np.argmax(prediction)
        disease = SKIN_CLASSES[pred]
        accuracy = prediction[0][pred]
        K.clear_session()
    return render_template('uploaded.html', title='Success', predictions=disease, acc=accuracy*100, img_file=f.filename)

**Comment by alvarolloret** [comment]
same error here

**Comment by johnc44** [comment]
I just started to get this error, then eventually captured the HTML response from google API and found that my IP address was being blocked because I'd been calling it too often.
