### ISSUE TITLE
Difference

### ISSUE THREAD

**Issue by fahamjv** [ssut/py-googletrans#176]
why it's so different with translate.google.com ?
for example :
"اصلا جالب به نظر نمیاد" translate by py-googletrans = "It did not seem"
"اصلا جالب به نظر نمیاد" translate by translate.google.com = "It doesn't look interesting at all"'
is there anything that could translate like  translate.google.com ?

**Comment by PasaOpasen** [comment]
Yes, I used TextBlob ([in this project](https://github.com/PasaOpasen/SpeechLogger)):

```python
from textblob import TextBlob

blob = TextBlob('اصلا جالب به نظر نمیاد')

blob.detect_language() # fa

to_eng = blob.translate(to='en')

str(to_eng)# It doesn't look interesting at all
```

It translates very well but I heard it's **obsolete API** (not recommented). And in my practice I saw **this problem with textblob**: u cannot try to translate too often (otherwise will be blocked for 24 hours) and sometimes after 15-20 translations u should wait next translation too long.

I think googletrans uses more simple model which give u a possibility to translate often (now I use it in [my Telegram bot](https://github.com/PasaOpasen/TranslatorBot)) but with less quality. And textblob works better if u don't need translating too often (maybe not more than 1 times per second)

**Comment by fahamjv** [comment]
> Yes, I used TextBlob ([in this project](https://github.com/PasaOpasen/SpeechLogger)):
> 
> ```python
> from textblob import TextBlob
> 
> blob = TextBlob('اصلا جالب به نظر نمیاد')
> 
> blob.detect_language() # fa
> 
> to_eng = blob.translate(to='en')
> 
> str(to_eng)# It doesn't look interesting at all
> ```
> 
> It translates very well but I heard it's **obsolete API** (not recommented). And in my practice I saw **this problem with textblob**: u cannot try to translate too often (otherwise will be blocked for 24 hours) and sometimes after 15-20 translations u should wait next translation too long.
> 
> I think googletrans uses more simple model which give u a possibility to translate often (now I use it in [my Telegram bot](https://github.com/PasaOpasen/TranslatorBot)) but with less quality. And textblob works better if u don't need translating too often (maybe not more than 1 times per second)

yes exactly . i'm using nltk after translation ... but the translation still not good

**Comment by PasaOpasen** [comment]
> > Yes, I used TextBlob ([in this project](https://github.com/PasaOpasen/SpeechLogger)):
> > ```python
> > from textblob import TextBlob
> > 
> > blob = TextBlob('اصلا جالب به نظر نمیاد')
> > 
> > blob.detect_language() # fa
> > 
> > to_eng = blob.translate(to='en')
> > 
> > str(to_eng)# It doesn't look interesting at all
> > ```
> > 
> > 
> > It translates very well but I heard it's **obsolete API** (not recommented). And in my practice I saw **this problem with textblob**: u cannot try to translate too often (otherwise will be blocked for 24 hours) and sometimes after 15-20 translations u should wait next translation too long.
> > I think googletrans uses more simple model which give u a possibility to translate often (now I use it in [my Telegram bot](https://github.com/PasaOpasen/TranslatorBot)) but with less quality. And textblob works better if u don't need translating too often (maybe not more than 1 times per second)
> 
> yes exactly . i'm using nltk after translation ... but the translation still not good

Try to use another APIs, maybe by amazon, microsoft, IBM, but it can be hard cuz of creating accounts and using keys...

**Comment by PasaOpasen** [comment]
Please let me know if u will find same simple API for translations

**Comment by fawazahmed0** [comment]
you have to install the latest version of py-googletrans and then it will work like translate.google.com
Here is how to update to the latest version:

`pip install git+https://github.com/ssut/py-googletrans.git`

Source:  https://github.com/ssut/py-googletrans/issues/152

**Comment by fahamjv** [comment]
> you have to install the latest version of py-googletrans and then it will work like translate.google.com
> Here is how to update to the latest version:
> 
> `pip install git+https://github.com/ssut/py-googletrans.git`
> 
> Source: #152

the version doesn't matter i guess

**Comment by fawazahmed0** [comment]
@fahamjv For me it did, at first the translation was not good, but after updating to latest version, it was working same as translate.google.com

**Comment by fawazahmed0** [comment]
@fahamjv 
![-2020-jun-8-002](https://user-images.githubusercontent.com/20347013/84087118-1b6f6680-aa07-11ea-8b1e-7036f2f6eb83.jpg)
