### ISSUE TITLE
Error in reading JSON file using json.loads()

### ISSUE THREAD

**Issue by udayk1809** [ssut/py-googletrans#177]
I have been getting the error as "Expecting value: line 1 column 1 (char 0)" in the line where I added "json.loads(f.readline())". I even added the encoding='utf8' but still won't work.
Please help.
`import json
import time
path = 'C:/Users/RAVI/Desktop/Final_Course1/datasets/review.json'
f=open(path,'r',encoding='utf8')`
`data=[]`
`for i in range(50000):`
     `data.append(json.loads(f.readline()))`

**Comment by 0mars** [comment]
It's fixed on master

**Comment by corwien** [comment]
i have same problem.

**Comment by 0mars** [comment]
you can either point pip to master or use my fork, I can release a fix soon

**Comment by corwien** [comment]
> you can either point pip to master or use my fork, I can release a fix soon

OK, thanks a lot.

**Comment by mihai10001** [comment]
Anything new about this issue? I'm still having problems ( probs because I got banned, even tho I didn't make a lot of requests, or disruptive requests, I'm just using it for a web application project ).
If it won't be resolved soon, I'll just go the official way. I wish I knew how to use the pipfile to point to your fork, but I sadly don't ( cuz i run a script from my docker file to install all requirements.txt at once )

**Comment by mihai10001** [comment]
On another note, using the bulk translate feature probably got me banned

**Comment by 0mars** [comment]
@mihai10001 you can use VPN

**Comment by 0mars** [comment]
can you open a PR for using proxies ?

**Comment by mihai10001** [comment]
Update: I've managed to pip install directly from master, which I didn't know was possible.
AND TO MY SURPRISE: BULK TRANSLATION WAS FIXED !
it no longer bans your IP while using it 🥇 
Congratz anyway, this updated version should also be published to pip package index

**Comment by ssut** [comment]
> Update: I've managed to pip install directly from master, which I didn't know was possible.
> AND TO MY SURPRISE: BULK TRANSLATION WAS FIXED !
> it no longer bans your IP while using it 🥇
> Congratz anyway, this updated version should also be published to pip package index

I will publish a new version of package soon. Sorry for you guys' inconvenience.

**Comment by ssut** [comment]
Closing in favor of #152.
