### ISSUE TITLE
long text  (>1745), en to zh_CN) throws ValueError exception

### ISSUE THREAD

**Issue by yucongo** [ssut/py-googletrans#18]
Tried with two different files in utf-8 format (Python 3.4,  32 bit Windows 7). Long text can probably be trimmed down to 1745 and some warning given, instead of sudden death.

import googletrans
googletrans.Translator('translate.google.cn')
text = '''...'''
texttr = translator.translate(text[:1745], dest='zh-CN')  # ok
texttr = translator.translate(text[:1746], dest='zh-CN')

ValueError                                Traceback (most recent call last)
<ipython-input-293-1df934595051> in <module>()
----> 1 texttr = translator.translate(text[:1746], dest='zh-CN')

d:\python34\lib\site-packages\googletrans\client.py in translate(self, text, dest, src)
    127
    128         origin = text
--> 129         data = self._translate(text, dest, src)
    130
    131         # this code will be updated when the format is changed.

d:\python34\lib\site-packages\googletrans\client.py in _translate(self, text, dest, src)
     79         r = self.session.get(url, params=params)
     80
---> 81         data = utils.format_json(r.text)
     82         return data
     83

d:\python34\lib\site-packages\googletrans\utils.py in format_json(original)
     49             text = text[:p] + states[j][1] + text[nxt:]
     50
---> 51     converted = json.loads(text)
     52     return converted
     53

d:\python34\lib\json\__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    316             parse_int is None and parse_float is None and
    317             parse_constant is None and object_pairs_hook is None and not kw):
--> 318         return _default_decoder.decode(s)
    319     if cls is None:
    320         cls = JSONDecoder

d:\python34\lib\json\decoder.py in decode(self, s, _w)
    341
    342         """
--> 343         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    344         end = _w(s, end).end()
    345         if end != len(s):

d:\python34\lib\json\decoder.py in raw_decode(self, s, idx)
    359             obj, end = self.scan_once(s, idx)
    360         except StopIteration as err:
--> 361             raise ValueError(errmsg("Expecting value", s, err.value)) from None
    362         return obj, end

ValueError: Expecting value: line 1 column 1 (char 0)

**Comment by ssut** [comment]
This is not an issue or a bug but an expected functionality of google translate. Check this out: https://github.com/ssut/py-googletrans#note-on-library-usage
