### ISSUE TITLE
Problem with proxy

### ISSUE THREAD

**Issue by rainsword** [ssut/py-googletrans#182]
When I create a Translator with a proxies, I fount it will not work properly.
```
proxies = {'http':'http://username:password@xxx:8080', 'https':'http://username:password@xxx:8080'}
translator = Translator(service_urls=['translate.google.com']， proxies = proxies)
```
I have debugged the code and found some problems:
1. at client.py
```
    def _translate(self, text, dest, src, override):
        token = self.token_acquirer.do(text)
        params = utils.build_params(query=text, src=src, dest=dest,
                                    token=token, override=override)

        url = urls.TRANSLATE.format(host=self._pick_service_url())
        r = self.session.get(url, params=params) # Here will call request, but not passing the proxies parameters to request, need change to
       r = self.session.get(url, params=params, proxies = self.session.proxies, verify = self.session.verify) 
```
2. at gtoken.py
```
    def _update(self):
        """update tkk
        """
        # we don't need to update the base TKK value when it is still valid
        now = math.floor(int(time.time() * 1000) / 3600000.0)
        if self.tkk and int(self.tkk.split('.')[0]) == now:
            return

        r = self.session.get(self.host) # Here alsocall request, but not passing the proxies parameters to request, need change to
        r = self.session.get(self.host, params=params, proxies = self.session.proxies, verify = self.session.verify)
```
3. at client.py
```
    def __init__(self, service_urls=None, user_agent=DEFAULT_USER_AGENT,
                 proxies=None, timeout=None): # Here suggest to add verfiy parameter

        self.session = requests.Session()
        if proxies is not None:
            self.session.proxies = proxies
        # if we have verify parameter, we may set it to self.session.verify
```

>       Because it may generate SSL error when use proxies with username & password.
>       Sometime it may resolved by install request's security package ：
>       `pip install -U request[security]`
>       But it may also generate some errors sometime, so we can set the verify to False

**Comment by ssut** [comment]
I think this issue can be closed if #181 is being done. Please note that there will be a breaking change in 3.0.0 release related to this issue.

**Comment by rainsword** [comment]
Thanks for your hard work.
I'm not sure whether the modify have been merged, but the code on the repository still have the problem.

**Comment by ssut** [comment]
It's not yet but soon, please wait for some time.

**Comment by rainsword** [comment]
OK， Thanks for your hard work.

**Comment by ssut** [comment]
3.0.0 has been released. Try this again using: https://www.python-httpx.org/advanced/#http-proxying.

**Comment by sicklife** [comment]
> 3.0.0 has been released. Try this again using: https://www.python-httpx.org/advanced/#http-proxying.

Is there an example?

**Comment by sicklife** [comment]
I figure it out...
It should be: 
`from httpcore import SyncHTTPProxy

from googletrans import Translator

translator = Translator(service_urls=['translate.google.cn'],
                        proxies={"https": SyncHTTPProxy((b'http', b'your.prxoy.ip.addr', 8888, b''))},
                        )`

**Comment by botzill** [comment]
> ```python
> {"https": SyncHTTPProxy((b'http', b'your.prxoy.ip.addr', 8888, b''))}
> ```

And password?
