### ISSUE TITLE
Pulling the "Translations of..." data as a way of correcting source language input

### ISSUE THREAD

**Issue by HadIKnown** [ssut/py-googletrans#185]
Please let me know if I've posted this in the wrong section. This is my first time interacting with a GitHub community :)

I have a Turkish source that, for whatever reason, decided to use English characters in place of uniquely Turkish ones. Google Translate is able to correct the errors, e.g. kopek to köpek and isirmaz to ısırmaz, and displays the corrections in the "Translations of..." tab below the destination language pain, as shown in the attached photo.

Can googletrans currently pull that information, i.e. does it pull the suggested correction? If so, how can I access it? If not, would this be a worthwhile feature to implement?

Thank you!

![Captura de pantalla 2020-06-15 a las 12 53 50](https://user-images.githubusercontent.com/17707797/84700777-a4efce80-af08-11ea-9444-e1d3fc6ae299.png)

**Comment by ssut** [comment]
You can access it using `.extra_data` of `Translated` results:

```python
>>> result = t.translate('안넝하세요.', 'ko')
>>> result.extra_data
{'translation': [['안넝하세요.', '안넝하세요.', None, None, 0], [None, None, 'anneonghaseyo.', 'anneonghaseyo.']], 'all-translations': None, 'original-language': 'ko', 'possible-translations': None, 'confidence': 1.0, 'possible-mistakes': ['<em>안녕하세요</em>.', '안녕하세요.', [1], None, None, False], 'language': [['ko'], None, [1.0], ['ko']], 'synonyms': None, 'definitions': None, 'examples': None, 'see-also': None}
>>> result.extra_data['possible-mistakes']
['<em>안녕하세요</em>.', '안녕하세요.', [1], None, None, False]
```

**Comment by HadIKnown** [comment]
Thank you so much! :)
