### ISSUE TITLE
Translation failing due to NoneType error

### ISSUE THREAD

**Issue by whereistejas** [ssut/py-googletrans#187]
I'm thinking that this error is similar to the errors we have seen before.

``` python
Traceback (most recent call last):
  File "translate.py", line 48, in <module>
    translations = trans.translate(entrytext, src=src_lang, dest=dest_lang)
  File "D:\Users\user1\AppData\Local\Programs\Python\Python38\lib\site-packages\googletrans\client.py", line 177, in translate
    translated = self.translate(item, dest=dest, src=src, **kwargs)
  File "D:\Users\user1\AppData\Local\Programs\Python\Python38\lib\site-packages\googletrans\client.py", line 185, in translate
    translated = ''.join([d[0] if d[0] else '' for d in data[0]])
TypeError: 'NoneType' object is not iterable
```

**Comment by terryyz** [comment]
What's your text input in this case?

**Comment by whereistejas** [comment]
It was just a normal text file in unicode. no special characters. Other people on my time also experienced the same issue. We use your module on one of our internal scripts. Really good work. Just wanted to say thank you!

If you want I can share the input text file.

**Comment by terryyz** [comment]
Thank you for letting me know! I tried to produce the same error as you listed above but just got something similar. I had the same `TypeError` msg when I put ["a", None] or [None] as my input. Your Pull Request would avoid the error. However, considering you were reading from a text file, there might be some different situations when encountering `None` type. If you could clarify your input or give just some samples referring to your case, that would help a lot :)

**Comment by whereistejas** [comment]
Sorry. I couldn't procure the input text file. What I can tell you is that it was an i18n file. I was translating from English to other languages.

**Comment by terryyz** [comment]
After discussing about this issue, we consider it as a personal issue. Not everyone wants to avoid interruption during translating. Some of them could may just mess their inputs up. Hence the interruption is essential. I'll also close the related pull request.
