### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by hontarenkoYana** [ssut/py-googletrans#189]
Hello! 

I have question about realization: did you use some cashing or else?
I have notice that using your library request to translate will be faster if it was made by same translator object sometime and RAM on my PC decrease.
If you using some cashing can I to disable it?

**Comment by ssut** [comment]
There is no such caching feature built in, so posting your code will help figure out if this is actually a library issue.

**Comment by hontarenkoYana** [comment]
I try to analyze and debug my code yesterday, and found that it is not you library. 
I didn't have time to close this issue, sorry for that.

P.S. Just want to say that your time provide good and easy to use library. Thanks!
