### ISSUE TITLE
Uncaught error on a simple translation (ver 1.1.1 via pip)

### ISSUE THREAD

**Issue by kmoppel** [ssut/py-googletrans#2]
$ translate -s ee ajuvaba
Traceback (most recent call last):
  File "/usr/local/bin/translate", line 38, in <module>
    main()
  File "/usr/local/bin/translate", line 27, in main
    result = translator.translate(args.text, dest=args.dest, src=args.src)
  File "/usr/local/lib/python3.4/dist-packages/googletrans/translator.py", line 92, in translate
    translated = data[0][0][0]
TypeError: 'NoneType' object is not subscriptable

**Comment by ssut** [comment]
As detected language, the language code of **estonian** is **et**, not **ee**.
If you try with **et**, it may be works.

Anyway, I updated the code to prevent invalid language codes being passed to the function, it would be appreciated when someone is trying to do so. (and it will be applied for next release!)
Thank you for your reporting. :)

**Comment by kmoppel** [comment]
Nice, thanks for the quick fix!
Hehe yes stumbled on it due to mistyping the language code, but then checked from [wikipedia](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) that "ee" is also a valid language code.

**Comment by ssut** [comment]
Ye, I'll consider to add a converter that substitutes for it. Thank you for your information. :+1:
