### ISSUE TITLE
Timeout after hundreds of translations

### ISSUE THREAD

**Issue by jiangwy17** [ssut/py-googletrans#202]
**Googletrans version:**

- [x] **3.x**
- [ ] **2.x**

**I'm submitting a ...** 

- [x] bug report
- [ ] feature request

**Current behavior:**

I am using Googletrans in China. I set the translator as `Translator(service_urls=['translate.google.cn'])` and It works. But when I try to translate thousands of individual sentences, exception `httpcore._exceptions.ConnectTimeout: timed out` always happen. If I translate one sentence each time, exception will happen after about 300 translations; if I try a batch of sentences (Advances Usage), exception happens and translation will never finish. I have tried to sleep for every 50 or 200 translations but it never worked. I want to know if there is a solution for this problem, otherwise I have to translate 300 sentences each time and It is time consuming.

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```python
translator = Translator(service_urls=['translate.google.cn'])
for index, row in data.iterrows():
    query, id = str(row['searched.query']).strip(), row['searched.clicked_content_id']
    if query != np.nan or id != np.nan:
        count += 1
        translation = translator.translate(query)
        print(str(count) + '   ', translation.origin, ' -> ', translation.text)
        query = translation.text
        result.append({'query': query, 'id': id})
```

**Other information:**

**Comment by terryyz** [comment]
If I'm right, there should be a limitation for times of translation. 300 is a reasonable number. When trying to translate tons of things, I usually will run the script in the Google Colab and record the number when it stops. After it stops, you can restart the kernel and start to translate the spot right after the number you recorded.

Otherwise, I may need to @ssut .

**Comment by jiangwy17** [comment]
> If I'm right, there should be a limitation for times of translation. 300 is a reasonable number. When trying to translate tons of things, I usually will run the script in the Google Colab and record the number when it stops. After it stops, you can restart the kernel and start to translate the spot right after the number you recorded.
> 
> Otherwise, I may need to @ssut .

Well, I have tried like this and it successed. I just wonder if there is a more elegant way or can we develop a new feature?

**Comment by terryyz** [comment]
We may find a better way to solve this but the limitation itself is implemented in the original Google Translation setting.

**Comment by ssut** [comment]
I have checked that the current implementation of the library does not support HTTP/2 so this may affect. I currently am working on fixing this issue with async/await support, and think this work may help handling this issue.

**Comment by jiangwy17** [comment]
> I have checked that the current implementation of the library does not support HTTP/2 so this may affect. I currently am working on fixing this issue with async/await support, and think this work may help handling this issue.

That's great, thank you!

**Comment by charlesfufu** [comment]
> If I'm right, there should be a limitation for times of translation. 300 is a reasonable number. When trying to translate tons of things, I usually will run the script in the Google Colab and record the number when it stops. After it stops, you can restart the kernel and start to translate the spot right after the number you recorded.
> 
> Otherwise, I may need to @ssut .
can you tell me how to restart the kernel? thx
