### ISSUE TITLE
the wrong of "json.decoder.JSONDecoderError:Expecting value: line1column 1(char 0)"

### ISSUE THREAD

**Issue by charlesfufu** [ssut/py-googletrans#203]
**Googletrans version:**
- [x] **3.x**
- [ ] **2.x**

**I'm submitting a ...** 

- [x] bug report
- [ ] feature request

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Comment by terryyz** [comment]
You may need to add more details according to the issue template. I could not tell anything from the error msg you provided.
