### ISSUE TITLE
Detect function not works normally

### ISSUE THREAD

**Issue by EugeneRymarev** [ssut/py-googletrans#205]
**Googletrans version:**
- [x] **3.x**
- [ ] **2.x**

**I'm submitting a ...** 
- [x] bug report
- [ ] feature request

**Current behavior:**
`Detected(lang=rubg, confidence=0.36821705)`

**Expected behavior:**
`Detected(lang=ru, confidence=0.36821705)`

**Steps to reproduce:**
**Related code:**
`translator.detect('тест')`

**Comment by terryyz** [comment]
Hi, `тест` exists both in Russian and Bulgarian. Thus, it gave you `rubg` as the result. However, it reminds me that perhaps a comma or a gap between `ru` and `bg` could be better :)

**Comment by EugeneRymarev** [comment]
@terryyz, why not return `List[Detect]` sorted by `confidence`?

**Comment by terryyz** [comment]
Good point! I'll make it happen :P

**Comment by EugeneRymarev** [comment]
> Good point! I'll make it happen :P

Then need reopen as feature request

**Comment by EugeneRymarev** [comment]
And add default parameter `best=True`.
If `best is True` then return only best match (first)
else return list of matches.

**Comment by ssut** [comment]
> And add default parameter `best=True`.
> 
> If `best is True` then return only best match (first)
> 
> else return list of matches.

I think it is very important to make the code to have consistency, always returning the same type on every function call, so I think it's enough to return a list ordered by confidence.

**Comment by EugeneRymarev** [comment]
> consistency

Ok. But code not consistent right now xD
When update?
