### ISSUE TITLE
network is unreachable after 100000 times

### ISSUE THREAD

**Issue by daixiangzi** [ssut/py-googletrans#206]
**Googletrans version:**
- [x] **3.x**
- [ ] **2.x**

**I'm submitting a ...** 

- [ ] bug report
- [x] feature request

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Comment by terryyz** [comment]
[](url) #202
