### ISSUE TITLE
is it possible to get Definition and Synonyms?

### ISSUE THREAD

**Issue by shahram7** [ssut/py-googletrans#208]
Hi there,

i'm using version 3.0.0 of googletrans and i need some helps.
when i set src and dest "en", i get the same word that i entered as input.
![image](https://user-images.githubusercontent.com/34509793/88918531-e1357f00-d269-11ea-8c27-d6cfbaab7c80.png)

i would like to know if is it possible to get Definitions and Synonyms as result?
![2020-07-30 13_25_53-Google Translate](https://user-images.githubusercontent.com/34509793/88918339-8f8cf480-d269-11ea-916f-2c4942783042.jpg)
 
thank you very much indeed.

Edit:
i have seen client.py . i dont know just how to use it :(
```
    def _parse_extra_data(self, data):
        response_parts_name_mapping = {
            0: 'translation',
            1: 'all-translations',
            2: 'original-language',
            5: 'possible-translations',
            6: 'confidence',
            7: 'possible-mistakes',
            8: 'language',
            11: 'synonyms',
            12: 'definitions',
            13: 'examples',
            14: 'see-also',
        }
```

**Comment by terryyz** [comment]
Hi, you can use `t.translate('Book').extra_data['definitions']` to get definitions :) Note there is something meaningless like `m_en_gbus0113460.006` in the result. You may need to select the expected answer from it by yourself.
