### ISSUE TITLE
I don't think HTTP/2 is being used

### ISSUE THREAD

**Issue by EtianAM** [ssut/py-googletrans#209]
**Googletrans version:**
- [x] **3.x**
- [ ] **2.x**

**I'm submitting a ...** 

- [x] bug report
- [ ] feature request

**Current behavior:**

If you check the protocol of the httpx response, it prints out that it is HTTP/1.1

**Expected behavior:**

Print HTTP/2

**Steps to reproduce:**

Edit client.py in function _translate to print the http version that the request use.

**Related code:**
client.py :

```
def _translate(self, text, dest, src, override):
	token = self.token_acquirer.do(text)
	params = utils.build_params(query=text, src=src, dest=dest,
								token=token, override=override)
		url = urls.TRANSLATE.format(host=self._pick_service_url())
	r = self.client.get(url, params=params)
	print(r.http_version) // Comprobation
		if r.status_code == 200:
		data = utils.format_json(r.text)
		return data
	else:
		if self.raise_exception:
			raise Exception('Unexpected status code "{}" from {}'.format(r.status_code, self.service_urls))
		DUMMY_DATA[0][0][0] = text
		return DUMMY_DATA
```

**Other information:**

In the [httpx page](https://www.python-httpx.org/http2/), it specifies that HTTP/2 must be enabled, which I don't think is done. ~~I don't know much about how this project or httpx works, however according to my tests, it only works using asyncio, which implies modifying an important part of the code.~~ (My mistake, I didn't read it right, it can be implemented without the asynchronous client)
Sorry if I'm the one who misinterprets something. Also sorry for bad english.

**Comment by ssut** [comment]
Thanks for opening an issue. This is a known issue we're currently looking into. The fix is still a work in progress and will be being updated soon with full asyncio support.

**Comment by EtianAM** [comment]
Thanks for answer, as a related error I would like to mention that the [API documentation](https://py-googletrans.readthedocs.io/en/latest/) says that HTTP/2 is through HYPER, isn't this incorrect?.
Thanks for the support.

**Comment by ssut** [comment]
It seems the documentation isn't updated. I've intended HTTP/2 working through [httpx](https://github.com/encode/httpx).

**Comment by EtianAM** [comment]
Oh, I know you use HTTPX, I mentioned it because since it's the documentation that the repository marks, I figured it would be handled by the repository.

**Comment by EtianAM** [comment]
For some reason now it did work just by adding the option. When I tried it that way it failed. (HTTPX version? I was using 1.13.x, now I am using 1.14.1)
```
def __init__(self, service_urls=None, user_agent=DEFAULT_USER_AGENT,
             raise_exception=DEFAULT_RAISE_EXCEPTION,
             proxies: typing.Dict[str, httpcore.SyncHTTPTransport] = None, timeout: Timeout = None):

    self.client = httpx.Client(http2 = True)
```
Well... Can you add this? It has nothing to do with asynchronous, although the documentation page says that it works better in the asynchronous client, there should be improvement even in the normal client.

**Comment by ssut** [comment]
I'll do that way. Thanks for letting me know.

@terryyz It seems we don't need to implement async feature for the present.
