### ISSUE TITLE
Inaccurate translation from Bengali to English(Reporting a bug)

### ISSUE THREAD

**Issue by tahfim63** [ssut/py-googletrans#210]
In Bengali, 1 = ১ , 2 = ২, 7 = ৭ , 8 = ৮, 
when I translate them independently it translates correctly, 
But when I try to translate ১৭,১৮,২৭,২৮, it translates to 16,16,26,26, 
I tried to make it right by specifying the service_urls, but it did not work. 
I am new to python, so still not familiar enough to work with source code.

**Comment by terryyz** [comment]
I believe this is a mistake originally from Google Translate. 
See the example: 
https://translate.google.com/?hl=en#view=home&op=translate&sl=bn&tl=en&text=%E0%A7%A7%E0%A7%AD
It somehow translated to 16 instead of 17...
If you want to get the correct result, you can try the following code:
```
from googletrans import Translator
t = Translator()
print(t.translate("১৭", src = "bn", dest = "bn").pronunciation)
```

**Comment by tahfim63** [comment]
Thanks a lot, that solved my issue. I did not assume it might work like that.
