### ISSUE TITLE
Make check for lists in bulk translation/detection include numpy ndarray

### ISSUE THREAD

**Issue by LAG1996** [ssut/py-googletrans#211]
**Googletrans version:**
- [ x ] **3.x**
- [ ] **2.x**

**I'm submitting a ...** 

- [ ] bug report
- [ x ] feature request

**Current behavior:**

When inputting a numpy ndarray into the `translate` and `detect` functions, the following exception is raised:
TypeError: ord() expected a character, but string of length 149 found.

Upon digging into the code, I found that the function only checks if the given array is an instance of python's `list`.

**Expected behavior:**

The functions should accept ndarrays as they are subscriptable, iterable just like lists, and ubiquitous.

**Steps to reproduce:**

As an argument to `translate` or `detect` use an ndarray rather than a list.

**Related code:**

```
import numpy as np

from googletrans import Translator
translator = Translator()

example_strings = np.array(['¡Hola Mundo!', 'El significado de la vida es 42.'])
translator.translate(example_strings)
```

A suggestion that I have to fix it would be to
1. move the check over to a utility function that can be used by the `translate` and `detect` methods.
2. include ndarrays in the check.

Also, I know that it's easy to convert the ndarray to a list, and that the example I gave above is a little contrived. This is more of a usability nitpick than anything. I just expect ndarrays to work identically to lists in most cases.

**Comment by terryyz** [comment]
We currently don't want to add more customized features since most of them can be fulfilled by simply adding some code along with this library.
