### ISSUE TITLE
Option to insert a custom language dictionary

### ISSUE THREAD

**Issue by ellandor** [ssut/py-googletrans#218]
**I'm submitting a ...** 

- [ ] bug report
- [x] feature request

I would like to know if it would be useful to add an option in `Translator.translate` to insert a customized dictionary in her language.

The standard dictionary used is translated only into English, but someone else might prefer to put the languages of the dictionary in her language.

An example of the dictionary translated into Portuguese
https://pastebin.com/RAYWPwsL

In addition to facilitating the use, because the person who does not know much English, needs to go to the standard dictionary and see what is the language to translate.

A example:

```python
Translator().translate(text='good morning', lang_dict=custom_dict, dest='portugues')
```
`lang_dict` would be the option to add the custom dictionary

And in the target language the person can already put the language in their own language, which in the case instead of putting **Portuguese** that would be in English, I can put **Portugues** and it won't change anything in the result

**Comment by terryyz** [comment]
I think the dict in `constants.py` called **`LANGUAGES`** is enough. It makes no difference if you use it in a script. Plus, it would be too long to be properly printed and selected when you use it in either the terminal or the Jupyter notebook/Colab.
