### ISSUE TITLE
Can this translate the content in the html code?

### ISSUE THREAD

**Issue by liushuo1** [ssut/py-googletrans#219]
Can this translate the content in the html code?

**Comment by terryyz** [comment]
The library doesn't support the direct html-formatted content translation. But you can make a script to make it happen :)

**Comment by vesper8** [comment]
@terryyz Could you possibly link to an existing script that takes care of translating content inside of html tags?

I'm noticing that without having to do anything extra it does mostly a good job of not messing up the html, but it's definitely not perfect and it does break in many instances

**Comment by milahu** [comment]
> an existing script that takes care of translating content inside of html tags?

solved in https://github.com/ssut/py-googletrans/issues/99#issuecomment-848714972
