### ISSUE TITLE
Some sentences from a provided list are left untranslated

### ISSUE THREAD

**Issue by nitin2212** [ssut/py-googletrans#221]
**Googletrans version:**
- [ 3.0.0 ]

**Current behavior:**
I tried to give a list of Japanese sentences and translate it one by one.
But some sentences are left untranslated

**Expected behavior:**
All sentences should be translated

**Related code:**

```
translator = Translator()
for sentence in ja_list:
    en_translation = translator.translate(sentence)

```

**Comment by ssut** [comment]
Could you provide the text list used for translation?

**Comment by pedrorio** [comment]
I can confirm this happens when translating a very big list of strings.

**Comment by imrek** [comment]
I can also confirm that this happens when translating in bulk. I have been trying to figure out how many characters Google accepts withouth throwing back 'empty' translations, but it isn't clear. Here's a sample of an untranslated sentence.

```
{
  "translation": [
    [
      "目尽无隐状",
      null,
      null,
      0
    ]
  ],
  "all-translations": null,
  "original-language": "en",
  "possible-translations": null,
  "confidence": 1,
  "possible-mistakes": null,
  "language": [
    [
      "en"
    ],
    null,
    [
      1
    ],
    [
      "en"
    ]
  ],
  "synonyms": null,
  "definitions": null,
  "examples": null,
  "see-also": null
}

```

**Comment by GorchompStomp** [comment]
This was my solution. I added a three second delay between each query. It took a long time, and I think a shorter delay would work too. I'm sure a more elegant solution exists, but this was quick and easy lol

```
from googletrans import Translator
import time

for word in word_list:
    time.sleep(3)
    trans = translator.translate(word['field1'])
    word['field2'] = trans.text

```

**Comment by polyzium** [comment]
Can confirm. I ran into this issue when making a Google Translate mod for a game:
```
SWWM_LORETXT_ZANAVETH3: 
english->german
german->kyrgyz
kyrgyz->french
french->filipino
filipino->catalan
catalan->english
Толук аты:
 Zanaveth Nekuraku III
Бүргөлөр:
 Бузуучу
 Unissix Bokurou Azadeku II
```

**Comment by JToward** [comment]
It happens to me as well.
