### ISSUE TITLE
How to pass parameters using proxy

### ISSUE THREAD

**Issue by ychrewd** [ssut/py-googletrans#227]
Source code：   
  :param proxies: proxies configuration.
                    Dictionary mapping protocol or protocol and host to the URL of the proxy
                    For example ``{'http': 'foo.bar:3128', 'http://host.name': 'foo.bar:4012'}``
  :type proxies: dictionary

   def __init__(self, service_urls=None, user_agent=DEFAULT_USER_AGENT,
                 raise_exception=DEFAULT_RAISE_EXCEPTION,
                 proxies: typing.Dict[str, httpcore.SyncHTTPTransport] = None, timeout: Timeout = None):

My way of passing parameters：

translator = Translator(proxies={'http': 'http://127.0.0.1:5000', 'https': 'https://127.0.0.1:5000'})

**Comment by Conight** [comment]
Issues already exists

https://github.com/ssut/py-googletrans/issues/182
