### ISSUE TITLE
seems google broke this(kinda)

### ISSUE THREAD

**Issue by nonetrix** [ssut/py-googletrans#236]
only works sometimes here is my code
`import googletrans
from googletrans import Translator

translator = Translator()

langs = translator.detect(['한국어', '日本語', 'English', 'le français'])
for lang in langs:
        print(lang.lang, lang.confidence)`

output

![kek](https://user-images.githubusercontent.com/45698918/98777972-434c6700-23b7-11eb-92b6-dedbf7e0a9c5.png)

**Comment by AbstractUmbra** [comment]
Duplicate of #234

**Comment by Shivster2401** [comment]
Glad I'm not the only one who's experiencing this.. Found any fixes or alternatives? :/
