### ISSUE TITLE
Can't auto deploy in empty virtualenv

### ISSUE THREAD

**Issue by mariusz-korzekwa** [ssut/py-googletrans#24]
Hi,
When I want to automatic deploy on server django project, which contains 'py-googletrans' library in requirements.txt, or simply run `pip install -r requirements.txt` on new empty virtualenv, I get:
```
$ pip install googletrans --no-cache-dir
Collecting googletrans
  Downloading googletrans-2.1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-5cKA5j/googletrans/setup.py", line 3, in <module>
        import googletrans
      File "googletrans/__init__.py", line 7, in <module>
        from googletrans.client import Translator
      File "googletrans/client.py", line 7, in <module>
        import requests
    ImportError: No module named requests
```
This error is caused by chain of imports:
 setup.py > __init__.py > client.py > requests
So setup.py run requests before instaling it.

I know that in [this](https://github.com/ssut/py-googletrans#installation) paragraph of docs @ssut remind that if I want to install 'googletrans' I must install requests before, but this is very uncomfortable during automatic deploy.

In my pull request, #23 I add solution on this issue.

**Comment by ssut** [comment]
I'm closing this issue because #23 has merged into the main branch.
