### ISSUE TITLE
Inappropriate behavior

### ISSUE THREAD

**Issue by KryakinVadim** [ssut/py-googletrans#241]
**Googletrans version:**
- [ ] **2.x**
- [x] **3.x**

**I'm submitting a ...** 

- [x] bug report
- [ ] feature request

![googletranserror1](https://user-images.githubusercontent.com/61296203/99525682-fae70780-29bb-11eb-972c-013fec6537f3.JPG)
![googletranserror2](https://user-images.githubusercontent.com/61296203/99525709-02a6ac00-29bc-11eb-8cf0-33796661bab5.JPG)
![googletranserror3](https://user-images.githubusercontent.com/61296203/99525734-089c8d00-29bc-11eb-8aa7-bab05f023c7b.JPG)
![googletranserror4](https://user-images.githubusercontent.com/61296203/99525860-3aadef00-29bc-11eb-9b77-76417caa9d99.JPG)

**Comment by ryanprater** [comment]
+1, using an example straight from the docs:
<img width="452" alt="image" src="https://user-images.githubusercontent.com/1916031/99532115-147c5500-29a4-11eb-8591-dd119d57ec96.png">

Still using v3.0.0, so I'm guessing this is on Google's side

**Comment by KryakinVadim** [comment]
it worked for me today
