### ISSUE TITLE
httpcore._exceptions.ConnectError: EOF occurred in violation of protocol (_ssl.c:748)

### ISSUE THREAD

**Issue by Crescentz** [ssut/py-googletrans#249]
python3

httpcore._exceptions.ConnectError: EOF occurred in violation of protocol (_ssl.c:748)

**Comment by dreamerriver** [comment]
i also encounter the same problem

**Comment by VictoriqueDeBlois** [comment]
i also encounter the same problem
httpcore._exceptions.ConnectError: EOF occurred in violation of protocol (_ssl.c:997)
