### ISSUE TITLE
error in googletrans 4.0.0rc1 translator

### ISSUE THREAD

**Issue by DanilKonon** [ssut/py-googletrans#257]
I tried the new version of googletrans 4.0.0rc1. 

```
translator = Translator(service_urls=['translate.google.com'])
res = translator.translate(text)
```

After some time an exception occurs: 
`AttributeError: 'Translator' object has no attribute 'raise_Exception'`

To fix this I need to execute this line:

`translator.raise_Exception = True`

And then the exception writes: `Exception: Unexpected status code "429" from ['translate.google.com']`

**Comment by setragw** [comment]
Happened to me as well. When I try to do either multiple translator.detect(), it occured

**Comment by velocityCavalry** [comment]
Same happened to me as well when executing the code snippet below:
```
def google_translate(word, code):
    translator = Translator()
    translator.raise_Exception = True
    translated = translator.translate(word, src=code, dest='en').text
    return translated
```

**Comment by 1nexoravel** [comment]
Hello there,  error 429 (Too Many Requests) it is a problem between your external IP and google. 
Just restarting my modem fixed the problem.

**Comment by emirpie2021** [comment]
Hi, I just used time.sleep(1) in translation loop. It gives more coffee time, works for me.

**Comment by jonas-nothnagel** [comment]
I have the same problem and even with changing IPs I am running into error 429. Is there a fix yet?

**Comment by haofanwang** [comment]
I also meet this problem.

**Comment by feihongloveworld** [comment]
same to me

**Comment by jonas-nothnagel** [comment]
Not a solution for this issue, but perhaps still helpful. I ended up using transformer based Neural Translation https://github.com/UKPLab/EasyNMT

It takes more time, but since it is a pre-trained model it is not dependent on some API we have no control over and the translation quality is fantastic.

**Comment by jonbesga** [comment]
I'm having this issue as well. Is there any fix coming up?

**Comment by SzczurekYT** [comment]
Me too have this issue, any fix?

**Comment by Perezmarc** [comment]
Same here

**Comment by DLesmes** [comment]
x100!!

I made more than 400 queries in a list comprehension perfectly it was ok and then I made another loop and the 'raise_Exception' appear again

some clue??

**Comment by EamonJarrett-Mann** [comment]
Wanted to comment so other people don't have to perform another search: currently google translate API allows 5 calls/second, caps it at 200k a day

**Comment by Rocky-04** [comment]
sleep(0.3)

**Comment by sachin-suresh-rapyuta** [comment]
> Not a solution for this issue, but perhaps still helpful. I ended up using transformer based Neural Translation https://github.com/UKPLab/EasyNMT
> 
> It takes more time, but since it is a pre-trained model it is not dependent on some API we have no control over and the translation quality is fantastic.

How to translate .po files using this?

**Comment by sachin-suresh-rapyuta** [comment]
> Hi, I just used time.sleep(1) in translation loop. It gives more coffee time, works for me.

Where do we add the time.sleep(1)?

**Comment by iHarshitTyagi** [comment]
The error "Exception: Unexpected status code "429" from ['translate.google.com']", you're getting because the function sent too many requests in a short span of time to google translate API. 
time.sleep(1) basically add 1 second between the executions. It doesn't necessarily be 1 you can supply time.sleep(0.1) in the function itself.

**Comment by SantiDianaClibrain** [comment]
Hi! Did time.sleep() work to anyone to make "infinite" requests to the google translate API?
