### ISSUE TITLE
googletrans 4.0.0-rc1 fails with TypeError: 'NoneType' object is not iterable on client.py:222

### ISSUE THREAD

**Issue by MaxBrain** [ssut/py-googletrans#260]
**Googletrans version:**
- **4.0.0rc1**

**I'm submitting a ...** 

- [x] bug report
- [ ] feature request

**Current behavior:**

```
python3
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from googletrans import Translator
>>> translator = Translator()
>>> print(translator.translate("Author", src="en", dest="de").text)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\Users\Max\AppData\Local\Programs\Python\Python37-32\lib\site-packages\googletrans\client.py", line 222, in translate
    translated_parts = list(map(lambda part: TranslatedPart(part[0], part[1] if len(part) >= 2 else []), parsed[1][0][0][5]))
TypeError: 'NoneType' object is not iterable
```

**Expected behavior:**

I expect the "Author" word in deuch

**Steps to reproduce:**

- Install googletrans 4.0.0-rc1
- Call python and make steps from "Current behavior"

**Comment by ssut** [comment]
<img width="1311" alt="Screen Shot 2020-12-13 at 5 25 21 AM" src="https://user-images.githubusercontent.com/2366668/101994173-a0fc0800-3d03-11eb-825e-d4470b2f15e1.png">

This probably is because of the gender-specific translate results. I will investigate and fix it soon.

**Comment by noaho** [comment]
I'm getting a similar issue, it seems whenever Google gives two results it fails. 

[['wrb.fr', 'MkEWBc', '[[null,null,null,[[[0,[[[null,3]\n]\n,[true]\n]\n]\n,[2,[[[null,4]\n,[4,24]\n]\n,[false,true]\n]\n]\n]\n,24]\n]\n,[[[null,"\\nPhraxāthity̒ kảlạng ca tkdin",null,null,null,[[null,[""]\n]\n,["\\n"]\n,["พระอาทิตย์กำลังจะตกดิน",["พระอาทิตย์กำลังจะตกดิน","ดวงอาทิตย์เป็นเรื่องเกี่ยวกับชุด"]\n]\n]\n]\n]\n,"th",1,"en"]\n]\n', None, None, None, 'generic'], ['di', 63], ['af.httprm', 63, '-9129644094679872904', 37]]
sequence item 0: expected str instance, NoneType found

**Comment by ssut** [comment]
@noaho Thanks for giving me the raw response. I'll fix it within a few days.

**Comment by noaho** [comment]
Thank you for the great project 😊

**Comment by JosMan94** [comment]
Hello! I have the same problem too.
@ssut  thank you very much for continuing with the project :D
Regards.

**Comment by ahmedbr** [comment]
Hi! any solution for this problem?

**Comment by ssut** [comment]
@ahmedbr I'm still working on it. Give me a little time please.

**Comment by ahmedbr** [comment]
> @ahmedbr I'm still working on it. Give me a little time please.

Thank you so much for your efforts bro, I've just faced the problem and wanted to ask whether it's been solved. Thanks again. 😄

**Comment by vbastianpc** [comment]
I think I have the solution. Replace this [line 222 of googletrans/client.py](https://github.com/ssut/py-googletrans/blob/28b85a807ddbb919df09fa4a8e7cef2fdde9f30c/googletrans/client.py#L222) with this
```
try:
    translated_parts = list(map(lambda part: TranslatedPart(part[0], part[1] if len(part) >= 2 else []), parsed[1][0][0][5]))
except TypeError: # because of the gender-specific translate results
    translated_parts = [ TranslatedPart(parsed[1][0][1][0], [parsed[1][0][0][0], parsed[1][0][1][0]]) ]
```
Gender-specific translations now work. 
```
>>> translator.translate("Author", src="en", dest="de").text
Autor
```

(This is my first comment on github, I don't know how to put this code snippet in your pull request)

**Comment by ahmedbr** [comment]
> I think I have the solution. Replace this [line 222 of googletrans/client.py](https://github.com/ssut/py-googletrans/blob/28b85a807ddbb919df09fa4a8e7cef2fdde9f30c/googletrans/client.py#L222) with this
> 
> ```
> try:
>     translated_parts = list(map(lambda part: TranslatedPart(part[0], part[1] if len(part) >= 2 else []), parsed[1][0][0][5]))
> except TypeError: # because of the gender-specific translate results
>     translated_parts = [ TranslatedPart(parsed[1][0][1][0], [parsed[1][0][0][0], parsed[1][0][1][0]]) ]
> ```
> 
> Gender-specific translations now work.
> 
> ```
> >>> translator.translate("Author", src="en", dest="de").text
> Autor
> ```
> 
> (This is my first comment on github, I don't know how to put this code snippet in your pull request)

Thanks for your reply, but this doesn't work for me

**Comment by Saravananslb** [comment]
Use this for google translation and it is working fine
https://pypi.org/project/pygoogletranslation

Thank me later

**Comment by mr2rm** [comment]
Hi, Still any solution to this issue?
Can I work on this?

**Comment by terryyz** [comment]
@mr2rm You are more than welcome to work on this :)

**Comment by kidburglar** [comment]
@ssut @ mr2rm Is there a reason it's not fixed yet? I ask because I tested the change of vbastianpc and it fixed the issue in my case.

@ahmedbr do you still have a way to reproduce your issue?

**Comment by ssikyou** [comment]
Same error here, it seems the issue still exsits.

**Comment by kidburglar** [comment]
@mr2rm 

I will try to find few case where I can reproduct the issue. I noted that it was because the gender like you said but also if you got an URL the answer from google is not the same.

**Comment by Luke8023** [comment]
incorrect from en to fr gives this error

**Comment by MaxBrain** [comment]
Actual code to reproduce
```
python3
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from googletrans import Translator
>>> translator = Translator()
>>> print(translator.translate("GREAT", src="en", dest="es").text)
```

**Comment by dandiep** [comment]
Still an issue. Any gendered word causes this. Another example: 

translator.translate("white", src="en", dest="es")

**Comment by lesleypotters** [comment]
I still have this problem when running the code like this:
`df['text_en'] = df['text'].apply(lambda x: translator.translate(x, src=es, dest='en').text )`

However, when I take out the `src=es` part, it does run - but it gets a timeout after 1,5h.

**Comment by gonzalo-cordova-pou** [comment]
`translator.translate("modern" , src="en", dest ='es')` return an Error:
`TypeError: 'NoneType' object is not iterable`
It looks like it has to do with the gender-specific translate. As "modern" in spanish is "moderna" and "moderno" depending on the gender

**Comment by MFRS** [comment]
No one ever updated this thread, so I discovered this from stackoverflow, but this issue has already been solved. 
If you do "pip install googletrans==3.1.0a0" it will give you the first result of a gender-specific translate, no longer giving you this error.

Source:
https://stackoverflow.com/questions/52455774/googletrans-stopped-working-with-error-nonetype-object-has-no-attribute-group

**Comment by danielpm307** [comment]
> No one ever updated this thread, so I discovered this from stackoverflow, but this issue has already been solved. If you do "pip install googletrans==3.1.0a0" it will give you the first result of a gender-specific translate, no longer giving you this error.
> 
> Source: https://stackoverflow.com/questions/52455774/googletrans-stopped-working-with-error-nonetype-object-has-no-attribute-group

The version googletrans==3.1.0a0 has this problem too .

**Comment by rodfranck** [comment]
Still an issue. Other examples:

translator.translate('ALPINE', src='en', dest='es')
translator.translate('Armenian', src='en', dest='es')

**Comment by edisonnery** [comment]
I don`t know if someone explains here what is the source of this problem.

I mapped that it happens when the translation returns two or more options.

An example is the word "Automatic". When this word is translated for Portuguese without context can return two options, "Automático" or "Automática".

I think that you can create a parameter to define which genre the code needs to return male or female.

**Comment by sachin-suresh-rapyuta** [comment]
Was there any solution to this error, other than the `try` block suggested here?

**Comment by ventz** [comment]
@MFRS Thank you - worked perfectly!

**Comment by vTuanpham** [comment]
> No one ever updated this thread, so I discovered this from stackoverflow, but this issue has already been solved. If you do "pip install googletrans==3.1.0a0" it will give you the first result of a gender-specific translate, no longer giving you this error.
> 
> Source: https://stackoverflow.com/questions/52455774/googletrans-stopped-working-with-error-nonetype-object-has-no-attribute-group

@MFRS This work for me, be sure to restart session if you are running on colab
