### ISSUE TITLE
NoneType return on Advanced Bulk version 4.0.0-rc1

### ISSUE THREAD

**Issue by AkmalPratama** [ssut/py-googletrans#264]
**Googletrans version:**
- [x] 4.0.0-rc1
- [ ] **3.x**
- [ ] **2.x**

**I'm submitting a ...** 

- [x] bug report
- [ ] feature request

**Current behavior:**

I tried to use the bulk translate from sample code on documentation page. The translate method return error
`TypeError: the JSON object must be str, bytes or bytearray, not 'NoneType'`

**Expected behavior:**

Should be same as written in documentation page. Bulk translate must return collection of translated object

**Steps to reproduce:**

Use list of string as an input parameter translate method 

**Related code:**

```
translator = Translator(service_urls=[
      'translate.google.com',
      'translate.google.co.kr',
    ])

translations = translator.translate(['The quick brown fox', 'jumps over', 'the lazy dog'], dest='ko')
for translation in translations:
    print(translation.origin, ' -> ', translation.text)
```

```
TypeError                                 Traceback (most recent call last)
<ipython-input-21-14c1e5590012> in <module>()
      4     ])
      5 
----> 6 translations = translator.translate(['The quick brown fox', 'jumps over', 'the lazy dog'], dest='ko')
      7 for translation in translations:
      8     print(translation.origin, ' -> ', translation.text)

1 frames
/usr/lib/python3.6/json/__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    346         if not isinstance(s, (bytes, bytearray)):
    347             raise TypeError('the JSON object must be str, bytes or bytearray, '
--> 348                             'not {!r}'.format(s.__class__.__name__))
    349         s = s.decode(detect_encoding(s), 'surrogatepass')
    350 

TypeError: the JSON object must be str, bytes or bytearray, not 'NoneType'
```

**Other information:**

**Comment by ShadowTeamCN** [comment]
same with me

**Comment by furkankadioglu** [comment]
Same here.

**Comment by zylkowski** [comment]
Same here.

**Comment by gpx135** [comment]
Same here.

**Comment by NikitaMishin** [comment]
same

**Comment by gpx135** [comment]
pip install googletrans==4.0.0rc1
this will fix the problem.

**Comment by AkmalPratama** [comment]
> pip install googletrans==4.0.0rc1
> this will fix the problem.

Not sure what you mean. The title of issue clearly stated that version

**Comment by DanilKonon** [comment]
I have the same error, but when the length of string is more than 5 000 characters.

**Comment by Jaspernwd** [comment]
Same problem

**Comment by kclamap** [comment]
**Not a fix** but I just had a glimpse at the source code and found that
```
class Translator:
  ...
  def translate(self, text, dest='en', src='auto', **kwargs):
    ...
    if isinstance(text, list):
      result = []
      for item in text:
          translated = self.translate(item, dest=dest, src=src, **kwargs)
          result.append(translated)
      return result
```
In other words, it just does a for loop to translate each string in the list if a list is passed in.
Since I was looking for ways to speed up my application, I try bulk translation. (I was doing a for loop by myself originally)
Now it turns out to me that whether it works or not has really no big deal......
I suggest you write the for loop in your code instead if you need it to work asap while waiting for a fix.

**Comment by Saravananslb** [comment]
Use this for google translation and it is working fine
https://pypi.org/project/pygoogletranslation

Thank me later

**Comment by AkmalPratama** [comment]
> Use this for google translation and it is working fine
> https://pypi.org/project/pygoogletranslation
> 
> Thank me later

yours doesn't working either, but that's another issue

```
AttributeError                            Traceback (most recent call last)
<ipython-input-69-9b258cdf2b47> in <module>()
      1 translator = Translator()
----> 2 translations = translator.translate(['this is google translation', 'Tamil language' ], dest='ta')
      3 for translation in translations:
      4   print(translation.origin, ' -> ', translation.text)

/usr/local/lib/python3.6/dist-packages/pygoogletranslation/translate.py in translate(self, text, src, dest)
     40 
     41     def translate(self, text, src='auto', dest='en'):
---> 42         text = text.replace('"', '')
     43         text = text.replace("'", "")
     44 

AttributeError: 'list' object has no attribute 'replace'
```

**Comment by Saravananslb** [comment]
Hi All,

We have updated our pygoogletranslation package to overcome the below issue,

1) bulk translation list error.
2) Character limit for old translation accept character upto 5000 but this package support unlimited translation 😛

For more information, visit our official pygoogletranslation page or GitHub page

Thanks,
Saravananslb

**Comment by Nirzak** [comment]
Same issue here.. trying to bulk transations.

**Comment by swaansverhuur** [comment]
same

**Comment by HRaf** [comment]
same issue 😒
