### ISSUE TITLE
IndexError for some texts 

### ISSUE THREAD

**Issue by DanilKonon** [ssut/py-googletrans#267]
Using googletrans-4.0.0rc1, I try to translate "40.41.43.44" and any string which has "//", but the error appears: IndexError: list index out of range
The problem is with this line in client.py:
translated_parts = list(map(lambda part: TranslatedPart(part[0], part[1] if len(part) >= 2 else []), parsed[1][0][0][5]))

**Comment by MyLtYkRiTiK** [comment]
I don't understand why, but code don't like dot without space.
So I simply add replace('.', '. ') and everything works fine

**Comment by terryyz** [comment]
Similar issue #278. Both issues result from the inappropriate way to parse the received data from `https://translate.google.com`.

**Comment by illusion-of-existence** [comment]
I am also having the same error. Could anyone suggest solution?
