### ISSUE TITLE
Problem with whitespaces

### ISSUE THREAD

**Issue by cryptoqube777** [ssut/py-googletrans#269]
I have encountered the following issue:
When translating from Russian to Ukrainian, the resulting text lacks whitespaces at all. All words are translated correctly, but they are all merged as a single word.
So in order to translate from Russian to Ukrainian, i have to do RU -> EN -> UK translation.
The version of googletrans is googletrans==4.0.0rc1

**Comment by sod1497** [comment]
It happens for CA -> ES too.
The workaround works like a charm! CA -> EN -> ES
Thanks @cryptoqube777 :)

**Comment by igor-kremin** [comment]
I am using workaround:
in text replace "spaces" to &nbsp; then in translated text &nbsp; replace  back to "spaces".
Although in translated text  "&nbsp;" may be slightly modified, pay attention.

**Comment by SeerBird** [comment]
Is there a clean workaround? The ones specified here don't really return the correct text
