### ISSUE TITLE
How many requests are allowed?

### ISSUE THREAD

**Issue by JafferWilson** [ssut/py-googletrans#27]
Please let me know if I am using the library for experimental purpose, till what count I can make requests.
I have more that 1 billion sentences to translate and analyze for my NLP project.
Kindly, suggest me.

**Comment by ssut** [comment]
I'm not sure how many reqeusts are allowed and haven't tested yet. I suggest you to do the test yourself.

**Comment by JafferWilson** [comment]
Thank you for your reply. I will certainly try.

**Comment by eoglethorpe** [comment]
@JafferWilson did you find anything out?
