### ISSUE TITLE
ImportError: cannot import name 'Translator'

### ISSUE THREAD

**Issue by shahreahang** [ssut/py-googletrans#276]
Hello,

I tried to install this package on both windows and Linux but on both of them i got this error :

Traceback (most recent call last):
  File "googletrans.py", line 1, in <module>
    from googletrans import Translator
  File "/home/py/googletrans.py", line 1, in <module>
    from googletrans import Translator
ImportError: cannot import name 'Translator'

in windows 
ImportError: cannot import name 'Translator' from 'googletrans' (C:\py projects\googletrans.py)

how can i fix that ?

**Comment by terryyz** [comment]
Hi @shahreahang, could you provide more details of your installation steps? This is not a usual Error during the installation.
