### ISSUE TITLE
googletrans==4.0.0-rc1 rate limit?

### ISSUE THREAD

**Issue by juncaofish** [ssut/py-googletrans#277]
It's likely the endpoint used by googletrans==4.0.0-rc1 version will encounter rate limit? 
httpcore._exceptions.ConnectError occurs when requests number reaches about 60000.
And we couldn't get response from the server any more.

**Comment by vesper8** [comment]
60000 what? characters? I'm trying to translate from a lambda function and I'm hitting the rate limit way faster than that.. I'm trying to understand how to get around that. I've tried adding delays, and doing smaller batches at a time.. but haven't figured out a reliable way yet

**Comment by aytimothy** [comment]
You want to be waiting about 20 seconds between per requests, on average.

**Comment by anhvu2501** [comment]
> You want to be waiting about 3 seconds between each request (20 per minute), on average. My scripts wait 4 seconds _after_ the return response is messaged. It's slower but it reliably _not_ hit the rate limit.

Hi, I am trying to use this api but I think it's about to reach the rate limit. Can you share your scripts that use this api and wait 4 seconds after each request?

**Comment by aytimothy** [comment]
> Hi, I am trying to use this api but I think it's about to reach the rate limit. Can you share your scripts that use this api and wait 4 seconds after each request?

Um...

```python
while True:
    res = translator.translate('guten morgen')
    print(res.text)
    sleep(4)
```

**Comment by anhvu2501** [comment]
> > Hi, I am trying to use this api but I think it's about to reach the rate limit. Can you share your scripts that use this api and wait 4 seconds after each request?
> 
> Um...
> 
> ```python
> while True:
>     res = translator.translate('guten morgen')
>     print(res.text)
>     sleep(4)
> ```
> 
> ?

thanks a lot
