### ISSUE TITLE
Getting "TypeError: 'NoneType' object is not iterable" when translating word "stripper" 

### ISSUE THREAD

**Issue by dominikpegler** [ssut/py-googletrans#278]
- Googletrans version: **4.0.0rc1**
- OS: **Ubuntu, Win10**

**Current behavior:**
When translating the word "stripper" from English to German or to French this error occurs. Translation of the same word to other languages such as Spanish, Russian, Romanian or Italian works.

```
>>> translator = Translator(service_urls=['translate.google.com','translate.google.at'])
>>> translator.translate("Stripper",src="en",dest="fr").text
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Pegler\Miniconda3\lib\site-packages\googletrans\client.py", line 222, in translate
    translated_parts = list(map(lambda part: TranslatedPart(part[0], part[1] if len(part) >= 2 else []), parsed[1][0][0][5]))
TypeError: 'NoneType' object is not iterable
```

**Comment by terryyz** [comment]
Hi @donkndetphone, there's a bug of getting the useful information inside `parsed` variable in the `client.py`. I'm trying to fix this.

**Comment by Aguiar16** [comment]
i get the same error when trying to translate the word "right" from english to portuguese

**Comment by pbtsrc** [comment]
The same for 
translator.translate('German', src='en', dest='es')

**Comment by benjaminvanrenterghem** [comment]
Translating "Miscellaneous" to lang=es triggers the same error.

**Comment by benjaminvanrenterghem** [comment]
![image](https://user-images.githubusercontent.com/42121860/128173229-998a5eb9-42eb-4b8d-9666-e1ea5ddb740c.png)
![image](https://user-images.githubusercontent.com/42121860/128173262-482b283e-1513-4df9-affd-a9d5a120e38a.png)
![image](https://user-images.githubusercontent.com/42121860/128173315-1d51d86d-ec66-48b3-a850-84bb6b3fb1ee.png)

This seems to be the cause, when it gives back a feminine and masculine form of the word when performed manually.

**Comment by sachin-suresh-rapyuta** [comment]
For anyone who is still facing the issue, I had to use the try block as discussed in this [thread](https://github.com/ssut/py-googletrans/issues/260#issuecomment-751521801). It seems to be working for me after adding the `try`.
