### ISSUE TITLE
extra data with command line

### ISSUE THREAD

**Issue by hosnas** [ssut/py-googletrans#282]
how I can get extra data like definitions with command line?

**Comment by terryyz** [comment]
Hi @hosnas , if you want to add more features to the command line tool, you can directly add more parsing args (e.g. `- def` for adding the definition feature) in `translate` file on the [`googletrans==3.1.0a0`](https://github.com/ssut/py-googletrans/blob/feature/enhance-use-of-direct-api/translate) branch. After modifying, you can `pip install .` to install locally for your own use.

I'm still a bit reluctant to add `extra_data` part to the command line tool as some attributes like `definition` contain unparsed data.
