### ISSUE TITLE
[4.0.0rc1]Result differ from google trans web: Inaccurate Result (Plsss How To Fix?)

### ISSUE THREAD

**Issue by neoryd** [ssut/py-googletrans#285]
**Googletrans version:**
- [x] **4.0.0rc1**
- [ ] **3.1.0a0**
- [ ] **3.0.0**
- [ ] **2.x**

**I'm submitting a ...** 

- [x] bug report
- [ ] feature request

**Current behavior:**
Result differ from google trans web: Inaccurate Result (Plsss How To Fix?)

**Other information:**

I Tried to compare the result to web version and it's very inaccurate compared to web version.

**Comment by jasonmbrown** [comment]
Ive also had this issue, I have only seen it once so far but i am going to add a logger and have to manually check all the translations now. My issue string is  '瑛 莉・・・・・・。' Upon translating all I get back is '・・・・・・.' When manually put into google translate it becomes 'Eri・・・・・・.'

**Comment by AlexandruCoser** [comment]
### Bug googletrans API version 4.0.0rc1

There is a translation problem if text exceeds a certain number of characters, although the result seems to happen randomly and not necessarily by the number of words. Are there certain keywords that trigger a bug in the API that leads only to the first 2 words as being translated? I am going to explain in detail below this behaviour:

`text = "problema aplicatie problema utilizare timp pacat rezolvat actualizari amintesc parte 123 aplicatie nu afiseaza data buton"`
`translator.translate(text, dest='en').text`

> **The output is only:** _'problem application'_

In a very strange way, if I just delete '123' string, it suddenly translates everything:
`text = "problema aplicatie problema utilizare timp pacat rezolvat actualizari amintesc parte aplicatie nu afiseaza data buton"`
`translator.translate(text, dest='en').text`
> **The output is:** _'Problem Application Problem Use Time Sitting Solved Updates Remember Application Do Not Show Data Button'_

Indeed, if I would just translate using Official Google Translate Web in the browser, the result is ok from the very beginning.
![image](https://user-images.githubusercontent.com/58252680/119660786-4af5c980-be38-11eb-9b6a-b3f9b7d08ab4.png)

Also, there is a strange behaviour of the output translated text from the API in that every word is capitalized. I know it's no biggy, we can use a lowercase() string method, but still, why is it happening?

I am looking forward to receiving fixes of the API in the near future.
Thank you for your time! All the best!
