### ISSUE TITLE
feature report

### ISSUE THREAD

**Issue by jhkd-kevin** [ssut/py-googletrans#287]
**Googletrans version:**
- [yes ] **4.0.0rc1**
- [ ] **3.1.0a0**
- [ ] **3.0.0**
- [ ] **2.x**

**I'm submitting a ...** 

- [ ] bug report
- [yes ] feature request

 As I follow you basic usage, 
after I enter:" translator.translate('안녕하세요.')",
 it reported that "httpcore._exceptions.ConnectError: [Errno 0] Error "

**Current behavior:**
My  python version is 3.7.3; Googletrans version is *4.0.0rc1*

**Expected behavior:**
if without bug, the result should follow the basic usage

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Comment by jrabensc** [comment]
Does it work on another machine or connection? Maybe you are rate-limited.

**Comment by dummerchen** [comment]
I encountered the same problem
