### ISSUE TITLE
Library no longer translated foreign languages properly

### ISSUE THREAD

**Issue by shift-eleven** [ssut/py-googletrans#288]
**Googletrans version:**
- [ ] **4.0.0rc1**
- [x] **3.1.0a0**
- [ ] **3.0.0**
- [ ] **2.x**

**I'm submitting a ...** 

- [x] bug report
- [ ] feature request

**Current behavior:**
Using this code 
```py
from googletrans import Translator

test = 'Bonjour'

tranlsator = Translator()

text_ouptut = tranlsator.translate(test)

print(text_ouptut.text)
```
The print statement outputs 'Bonjour' rather than 'hello'

And the same happens with other languages as well

After checking around with the `detect` function, it seems its detecting them as English although they are in French, this is weird as up until now I wasn't running into this issue

**Comment by dinitanomi** [comment]
Same, it's translated 200-300 strings, and then always return original text.
Changing user-agent or using timeout does not affect, but in web-browser google still translating text.

@shift-eleven 
If my case, when i use `translator = Translator(raise_exception=True)` - that raise error 429.

**Comment by shift-eleven** [comment]
Switching to 4.0.0rc1 seems to do the trick for me and it started translating properly again
