### ISSUE TITLE
About using a proxy to solve the problem of IP being blocked due to too many requests

### ISSUE THREAD

**Issue by qinghuan1998** [ssut/py-googletrans#289]
**Googletrans version:**
- [x] **4.0.0rc1**
- [ ] **3.1.0a0**
- [ ] **3.0.0**
- [ ] **2.x**

**I'm submitting a ...** 

- [x] feature request
- [ ] bug report

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
translator = Translator(service_urls=["translate.google.cn"],
                        proxies={"192.168.0.1": SyncHTTPTransport()})
```

**Other information:**

When using the GoogleTrans library, IP will be limited if there are too many requests or translation characters, so I want to continue the translation through the proxy, but how to set the proxy for this interface? The parameter types of example and typing given in client.py are not the same.
In client.py, the example in line 53 and the parameter type restrictions in line 62 seem to be different.
line 53: For example ``{'http': 'foo.bar:3128', 'http://host.name': 'foo.bar:4012'}``
line 62:proxies: typing.Dict[str, httpcore.SyncHTTPTransport] = None
Could you please tell me how to set up the IP proxy， thanks.

**Comment by mowshon** [comment]
@ssut The proxy setting doesn't work at all. I try to fix it myself, but it doesn't work. I would be glad if you take a look at this problem.

**Comment by qinghuan1998** [comment]
The problem has been solved, the example is as follows：
from googletrans import Translator
from httpcore import SyncHTTPProxy

```
translator = Translator(service_urls=["translate.google.cn"],
                        proxies={"http": SyncHTTPProxy((b'http', b'127.0.0.1', 7890, b''))})
res = translator.translate("hello,world!", src="en", dest="zh-cn").text
```

Need to import SyncHTTPProxy library. 
The parameter description is as follows：
 *** **proxy_url** - `Tuple[bytes, bytes, Optional[int], bytes]` - The URL of
    the proxy service as a 4-tuple of (scheme, host, port, path).**
The scheme parameter is the protocol used.
The path parameter is the domain name, which is empty by default.
My proxy port is 7890 of this machine, just change it to the port monitored by vpn.

**Comment by AliAkhtari78** [comment]
Same issue here.
is there any way to use proxy list?
