### ISSUE TITLE
Do I still need "py-googletrans-master.zip" if I have already installed the library it in cmd?

### ISSUE THREAD

**Issue by me-suzy** [ssut/py-googletrans#293]
hello. I install the last version of googletrans on CMD, by the command below:

`py -m pip install googletrans==4.0.0rc1`

Do I still need "py-googletrans-master.zip" if I have already installed the library it in cmd? Does it help me with something extra?

**Comment by ZhymabekRoman** [comment]
> Do I still need "py-googletrans-master.zip" if I have already installed the library it in cmd?

No
