### ISSUE TITLE
"GoogleTrans as a command line application"

### ISSUE THREAD

**Issue by AlkisPis** [ssut/py-googletrans#298]
```
$ translate -h
usage: translate [-h] [-d DEST] [-s SRC] [-c] text
```
Where is this 'translate' executable??? It seems that it is stored in the PATH (environment) ... miraculously. And it looks like it is considered so obvious that no one tells anything about it!

**Comment by danilobatistaqueiroz** [comment]
I searched using: `sudo find -name "translate" -type f` and I didn't find anything in my filesystem.

**Comment by AlkisPis** [comment]
Indeed, there's nowhere an executable file! The _'translate'_ command refers to a file, **'translation.py'** which is executed with _'python.exe'_ !!! I found this file in the Web. (It's not part of the _'googletrans'_ installation.) 
A lot of times, I really wonder about the IQ of the people writing documentations!
