### ISSUE TITLE
Translator returns input

### ISSUE THREAD

**Issue by Sapereaude9** [ssut/py-googletrans#300]
I'm using version 3.1.0a0 of the googletrans module, about which I would like to report a bug. 

I find that while the module works fine for the first ten requests or so, it then fails to translate. It does not return an error message of any sort, but just returns my own text back at me, untranslated. For instance, _chaussette_ is the French word for sock, but it fails to return that string:

![image](https://user-images.githubusercontent.com/86801559/124178887-ecacae00-daa9-11eb-8805-a698b6fe2fd3.png)

I'm using a generic script from the internet to generate the above output (https://pythongeeks.org/python-language-translator/), but I have exactly the same problem with my own script. I've checked the internet, but all I can see is internal bugs that return an error message of some sort, not the logic error I'm describing. I'd guess that Google dislikes the requests and is blocking them, but even after using a VPN and changing the source network many times, the problem continues.

**Comment by Sapereaude9** [comment]
I resolved this by simply switching my code over to the https://github.com/lushan88a/google_trans_new package, which is working for now.

**Comment by michalis001** [comment]
I've got the same issue

**Comment by michalis001** [comment]
and google_trans_new isn't working either for me. For google_trans I downloaded the fix recommended on AttributeError: nonetype object.... but that is still giving this error here, that It isn't translating and just outputing the input. Could you please fix it

**Comment by akshay-pande** [comment]
I have the same issue with googletrans==3.1.0a0

**Comment by akshay-pande** [comment]
The import for the google_trans_new package is not working
```

import google_trans_new
Traceback (most recent call last):
  File "<pyshell#25>", line 1, in <module>
    import google_trans_new
  File "C:\Python39\lib\site-packages\google_trans_new\__init__.py", line 7, in <module>
    from .google_trans_new import google_translator
  File "C:\Python39\lib\site-packages\google_trans_new\google_trans_new.py", line 4, in <module>
    import json, requests, random, re
ModuleNotFoundError: No module named 'requests'
```

**Comment by eyaler** [comment]
same issue
