### ISSUE TITLE
TypeError: the JSON object must be str, bytes or bytearray, not NoneType

### ISSUE THREAD

**Issue by hu0514** [ssut/py-googletrans#301]
File "/data/leisu/leisu_env/lib/python3.7/site-packages/googletrans/client.py", line 219, in translate
    parsed = json.loads(data[0][2])
  File "/data/local/python3.7/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType

**Comment by qinghuan1998** [comment]
我遇到了同样的报错，经过检测发现是翻译的字符数超过5000或者传入的是""空字符串就会有这样的报错。但API文档中显示单个文本最大翻译字符上限为15K，我也有点迷糊，想到issue中寻找答案来着，，，

**Comment by alperenkaplan** [comment]
I believe you encounter this issue because your text is too long.I think documentation says the character limit is15k but I encounter the same problem when I send anything longer than 5k. Try to send your text in 5k chunks and see if you still have the issue. Make sure the chunks end with complete sentences tho. Then you can concatenate the results

**Comment by benjaminvanrenterghem** [comment]
Your content is too long, I recommend using something smaller than 5000 as mentioned above.
Break your content up into chunks and translate them, example below:

```from googletrans import Translator as GoogleTranslator
from time import sleep
import backoff

class Translator:
    def __init__(self):
        self.client = GoogleTranslator()
        self.sleep_in_between_translations_seconds = 10
        self.source_language = "en"
        self.max_chunk_size = 4000

    def __createChunks(self, corpus):
        chunks = [corpus[i:i + self.max_chunk_size] for i in range(0, len(corpus), self.max_chunk_size)]
        return chunks

    def __sleepBetweenQuery(self):
        print('Sleeping for {}s after translation query..'.format(self.sleep_in_between_translations_seconds))
        sleep(self.sleep_in_between_translations_seconds)

    @backoff.on_exception(backoff.expo, Exception, max_tries=150)
    def Translate(self, content, dest_language_code):
        try:
            print('Attempting to translate to lang={}'.format(dest_language_code))
            if len(content) > self.max_chunk_size:
                print('Warning: Content is longer than allowed size of {}, breaking into chunks'.format(self.max_chunk_size))
                results_list = []
                concatenated_result = ""

                original_chunks = self.__createChunks(content)
                for i in original_chunks:
                    r = self.client.translate(i, dest=dest_language_code, src=self.source_language)
                    self.__sleepBetweenQuery()
                    results_list.append(r.text)

                for i in results_list:
                    concatenated_result += i

                return concatenated_result
            else:
                res = self.client.translate(content, dest=dest_language_code, src=self.source_language)
                self.__sleepBetweenQuery()
                return res.text
        except Exception as e:
            print(e)
            raise e```

**Comment by New-dev0** [comment]
I am getting this error for small text too (below 500 characters ) 😕

**Comment by benjaminvanrenterghem** [comment]
Apparently this error also occurs when a bunch of whitespace / no content to actually translate is present. Something to keep in mind.

**Comment by NawtJ0sh** [comment]
if yall cant get this working, you can try this instead https://github.com/ssut/py-googletrans/issues/268

**Comment by Secret-chest** [comment]
It also happens if the string is empty. I translate from a JSON file, add this line before translating:
```python
if sourceTranslation == "" or sourceTranslation is None:
```

**Comment by ganbayar-damboo** [comment]
result=df.to_json(orient="index",default_handler=str).encode('utf-8')

**Comment by Absolutorcinus** [comment]
I am trying to get the source language  from a sentence:

`langs = translator.detect(['Hehehe, di daerah '])
        for lang in langs:
             print(lang.lang, lang.confidence)`

i get the following Error:

---------------------------------------------------------------------------

TypeError                                 Traceback (most recent call last)

[<ipython-input-31-9e699853a791>](https://localhost:8080/#) in <module>()
----> 1 langs = translator.detect(['Hehehe, di daerah '])
      2 for lang in langs:
      3   print(lang.lang, lang.confidence)

2 frames

[/usr/local/lib/python3.7/dist-packages/googletrans/client.py](https://localhost:8080/#) in detect(self, text)
    367 
    368     def detect(self, text: str):
--> 369         translated = self.translate(text, src='auto', dest='en')
    370         result = Detected(lang=translated.src, confidence=translated.extra_data.get('confidence', None), response=translated._response)
    371         return result

[/usr/local/lib/python3.7/dist-packages/googletrans/client.py](https://localhost:8080/#) in translate(self, text, dest, src)
    217 
    218         data = json.loads(resp)
--> 219         parsed = json.loads(data[0][2])
    220         # not sure
    221         should_spacing = parsed[1][0][0][3]

[/usr/lib/python3.7/json/__init__.py](https://localhost:8080/#) in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    339     else:
    340         if not isinstance(s, (bytes, bytearray)):
--> 341             raise TypeError(f'the JSON object must be str, bytes or bytearray, '
    342                             f'not {s.__class__.__name__}')
    343         s = s.decode(detect_encoding(s), 'surrogatepass')

TypeError: the JSON object must be str, bytes or bytearray, not NoneType
