### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'     on newly installed library

### ISSUE THREAD

**Issue by vega0** [ssut/py-googletrans#302]
└─$ python3.9 translate_to_other_languages.py                                                                           Traceback (most recent call last):                                                                                        File "/mnt/d/translate_to_other_languages.py", line 5, in <module>                                                        translator.detect('이 문장은 한글로 쓰여졌습니다.')                                                                   File "/home/kali/.local/lib/python3.9/site-packages/googletrans/client.py", line 255, in detect                           data = self._translate(text, 'en', 'auto', kwargs)                                                                    File "/home/kali/.local/lib/python3.9/site-packages/googletrans/client.py", line 78, in _translate                        token = self.token_acquirer.do(text)                                                                                  File "/home/kali/.local/lib/python3.9/site-packages/googletrans/gtoken.py", line 194, in do                               self._update()                                                                                                        File "/home/kali/.local/lib/python3.9/site-packages/googletrans/gtoken.py", line 62, in _update                           code = self.RE_TKK.search(r.text).group(1).replace('var ', '')                                                      AttributeError: 'NoneType' object has no attribute 'group'    

import googletrans
from googletrans.constants import LANGUAGES 

translator = googletrans.Translator()
translator.detect('이 문장은 한글로 쓰여졌습니다.')
translator.translate('안녕하세요.')
for short_code in LANGUAGES.keys():
	print(short_code)
	try:
		print(translator.translate("хуй", dest=short_code))
	except Exception as e:
		print(e)

**Comment by epugh** [comment]
I just ran into this as well ;-(

**Comment by vega0** [comment]
> I just ran into this as well ;-(

What version on python you use?

**Comment by rochanaph** [comment]
as mentioned in [https://github.com/ssut/py-googletrans/issues/234](url)
this worked for me
`pip install googletrans==4.0.0-rc1 `

**Comment by vega0** [comment]
> as mentioned in #234
> this worked for me
> `pip install googletrans==4.0.0-rc1 `

Used version 3.0.0, fixed with forced update to 4.0.0
