### ISSUE TITLE
Code getting rate limited

### ISSUE THREAD

**Issue by krishyadav007** [ssut/py-googletrans#308]
**Googletrans version:**
- [ ] **4.0.0rc1**
- [X] **3.1.0a0**
- [ ] **3.0.0**
- [ ] **2.x**

**I'm submitting a ...** 
- [X] bug report
- [ ] feature request

**Current behavior:**
The code is getting rate limited by google, 
```
    raise Exception('Unexpected status code "{}" from {}'.format(
Exception: Unexpected status code "429" from ['translate.googleapis.com']
```

**Expected behavior:**
How many requests should we do in one min, or after how much time, should we request? Couldn't find in docs

**Steps to reproduce:**
Try running code around 50 times a min

**Related code:**
```
translator = Translator(raise_exception=True)
print(translator.translate("Hi, Its me your friend, batman", dest=lang))
```

**Other information:**
https://github.com/ssut/py-googletrans/issues/297

**Comment by benjaminvanrenterghem** [comment]
Sleeping for 7 seconds between queries seems to work fine without getting ratelimited. Alternatively, pass along proxies to your Translator:

How its implemented: 
https://github.com/ssut/py-googletrans/blob/d15c94f176463b2ce6199a42a1c517690366977f/googletrans/client.py#L60
This library uses httpx, more info on how to construct your proxy dictionary can be found there: 
https://www.python-httpx.org/advanced/

**Comment by krishyadav007** [comment]
Thanks, but 7 seconds didn't work, though 10 secs working fine, thankyou for your help
