### ISSUE TITLE
Unable to translate.. showing : Handshake operation timeout

### ISSUE THREAD

**Issue by Priyavrat007** [ssut/py-googletrans#312]
ConnectTimeout: _ssl.c:1059: The handshake operation timed out.
![googletrans error](https://user-images.githubusercontent.com/43645833/132095799-99137575-14c6-449b-842a-b55370dce6a9.jpg)

**Comment by CN-COTER** [comment]
so do i.

**Comment by vlasvlasvlas** [comment]
same here
