### ISSUE TITLE
Is this package deprecated?

### ISSUE THREAD

**Issue by bensonchow123** [ssut/py-googletrans#318]
When I run it, it just return "AttributeError: 'NoneType' object has no attribute 'group' "
Is there a maintained fork that i can use?

**Comment by msr8** [comment]
I think its depreciated since this problem was present even in May, here's how to "temporarily solve" it: https://github.com/ssut/py-googletrans/issues/280

**Comment by benjaminvanrenterghem** [comment]
Sadly enough it seems so.

**Comment by jasperan** [comment]
@msr8 it's still working with the version you referenced
