### ISSUE TITLE
Demo code is not working.

### ISSUE THREAD

**Issue by pandya6988** [ssut/py-googletrans#319]
Hello, 

I am not able to run demo code from you. 

```
from googletrans import Translator
translator = Translator()
translator.translate('안녕하세요.')
```

Error: 
`AttributeError: 'NoneType' object has no attribute 'group'`

**Googletrans version:**
- [ ] **4.0.0rc1**
- [ ] **3.1.0a0**
- [ ] **3.0.0**
- [ ] **2.x**

**I'm submitting a ...** 

- [ ] bug report
- [ ] feature request

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Comment by jasperan** [comment]
Same issue. If you have any news please mention me

**Comment by jasperan** [comment]
Nevermind, found a "temporary fix" @pandya6988 

Install and use this googletrans version:

`pip install googletrans==3.1.0a0`

**Comment by CJSparrow** [comment]
`AttributeError: 'NoneType' object has no attribute 'group'`

**Comment by EAScript** [comment]
> Nevermind, found a "temporary fix" @pandya6988
> 
> Install and use this googletrans version:
> 
> `pip install googletrans==3.1.0a0`

Thanks it works just please update the main package

**Comment by jasperan** [comment]
It's not me, I'm just a regular user like you @EAScript
