### ISSUE TITLE
httpcore._exceptions.ConnectTimeout: _ssl.c:1029: The handshake operation timed out

### ISSUE THREAD

**Issue by WBWhiteBeard** [ssut/py-googletrans#320]
httpcore._exceptions.ConnectTimeout: _ssl.c:1029: The handshake operation timed out。

excuse me,sir!
     some errors occur. 
![image](https://user-images.githubusercontent.com/19382492/141719184-eeda80c3-defd-42db-baff-7be1010007c8.png)

**Comment by EugeneRymarev** [comment]
Confirm

**Comment by EugeneRymarev** [comment]
> httpcore._exceptions.ConnectTimeout: _ssl.c:1029: The handshake operation timed out。
> 
> excuse me,sir! some errors occur. ![image](https://user-images.githubusercontent.com/19382492/141719184-eeda80c3-defd-42db-baff-7be1010007c8.png)

You found any solution of this error?

**Comment by EugeneRymarev** [comment]
@ssut, any updates?
