### ISSUE TITLE
Language detection faulty

### ISSUE THREAD

**Issue by jasperan** [ssut/py-googletrans#321]
Right now, I'm trying to execute the code with several spanish texts, and it's detecting english with 100% confidence. I thought you should know.

`en
Detected(lang=en, confidence=1)
Translated(src=en, dest=en, text=@GoDsKiNg19 Gracias por la información. Por favor siga nuestra cuenta @AskPlayStation para mayor asistencia vía mensajes directos., pronunciation=@GoDsKiNg19 Gracias por la información. Por favor siga nuestra cuenta @AskPlayStation para mayor asistencia vía mensajes directos., extra_data="{'translat...")
en
Detected(lang=en, confidence=1)
Translated(src=en, dest=en, text=@Gael36988988 Lamentamos que tenga este problema. Visite este enlace y siga los pasos para ese código específico:  https://t.co/124Egi2Mzs, pronunciation=@Gael36988988 Lamentamos que tenga este problema. Visite este enlace y siga los pasos para ese código específico:  https://t.co/124Egi2Mzs, extra_data="{'translat...")
en
Detected(lang=en, confidence=1)
Translated(src=en, dest=en, text=@Shampu07 Lamentamos que tenga problemas al intentar actualizar la información de facturación. Encuentre información para saber cómo agregar PayPal aquí:  https://t.co/qzxpmKL2wI  1/2, pronunciation=@Shampu07 Lamentamos que tenga problemas al intentar actualizar la información de facturación. Encuentre información para saber cómo agregar PayPal aquí:  https://t.co/qzxpmKL2wI  1/2, extra_data="{'translat...")
en
Detected(lang=en, confidence=1)
Translated(src=en, dest=en, text=@omhsev210 Lamentamos que tenga este problema. Visite este enlace y siga los pasos para ese código específico:  https://t.co/QVJC35Yggj, pronunciation=@omhsev210 Lamentamos que tenga este problema. Visite este enlace y siga los pasos para ese código específico:  https://t.co/QVJC35Yggj, extra_data="{'translat...")
en
Detected(lang=en, confidence=1)
Translated(src=en, dest=en, text=@PonchoRF007 Hola, gracias por contactarnos. Lamentamos saber que tienes problemas con tu juego. ¿Has intentado los pasos en este enlace:  https://t.co/QVJC35Yggj? Dejanos saber el resultado., pronunciation=@PonchoRF007 Hola, gracias por contactarnos. Lamentamos saber que tienes problemas con tu juego. ¿Has intentado los pasos en este enlace:  https://t.co/QVJC35Yggj? Dejanos saber el resultado., extra_data="{'translat...")
en
Detected(lang=en, confidence=1)
Translated(src=en, dest=en, text=@Abelgb_18 Hola Abel, gracias por contactarnos. Lamentamos saber que tienes problemas con tu juego. ¿Has intentado los pasos en este enlace:  https://t.co/QVJC35Yggj? Dejanos saber el resultado., pronunciation=@Abelgb_18 Hola Abel, gracias por contactarnos. Lamentamos saber que tienes problemas con tu juego. ¿Has intentado los pasos en este enlace:  https://t.co/QVJC35Yggj? Dejanos saber el resultado., extra_data="{'translat...")
en
Detected(lang=en, confidence=1)
Translated(src=en, dest=en, text=@PateaKulos Gracias. Siguenos a traves de Twitter para poder enviarte un Mensaje Privado con instrucciones., pronunciation=@PateaKulos Gracias. Siguenos a traves de Twitter para poder enviarte un Mensaje Privado con instrucciones., extra_data="{'translat...")
en`

**Comment by shohrehhd** [comment]
Same happens to me but randomly.
