### ISSUE TITLE
Idea: Return extra_data as dictionary instead of lists?

### ISSUE THREAD

**Issue by bai-yi-bai** [ssut/py-googletrans#324]
Edit: Using version 3.1.0a

I wonder if it is possible to have the library parse extra_data into a more convenient structure instead of a tree of nested lists. I had to write a lot of code to parse extra_data into a more usable list of dictionaries. I think other uses may benefit from getting "tagged" data. I couldn't find any documentation about the returned data format and client.py doesn't explain the extra_data structure beyond the initial categories. 

I fear that my assumptions on my limited testing might not be enough.
Although, I did find this project which provides sorted json: https://github.com/FreddieDeWitt/extended-google-translate-api
It'd be nice to have a similar sorted output.

### Current Output of extra_data

```
translator = googletrans.Translator()
result = translator.translate(text=text, src=src, dest=dest)
main_translation = {
        "input_text": text,
        "src":src,
        "dest":dest,
        "translated_text": result.text,
        "pronunciation":result.pronunciation,
    }
    print(main_translation)
print(result.extra_data['all-translations'])
```

{'input_text': 'test', 'src': 'en', 'dest': 'zh-tw', 'translated_text': '測試', 'pronunciation': 'Cèshì'}

I'm not sure what the "None" values are, so I just discard them. Other categories have even more complex structures.

[['noun', ['測試', '試驗', '試', '實驗', '考試', '考驗', '測驗'], [['測試', ['test', 'examination'], None, 0.61608213], ['試驗', ['test', 'experiment', 'tentative'], None, 0.21967085], ['試', ['test', 'examination', 'experiment', 'exam', 'fitting'], None, 0.020115795], ['實驗', ['experiment', 'test'], None, 0.015912903], ['考試', ['examination', 'exam', 'test'], None, 0.012588142], ['考驗', ['test', 'trial', 'ordeal'], None, 0.012588142], ['測驗', ['test', 'quiz'], None, 0.004559123]], 'test', 1], ['verb', ['檢驗', '試', '考', '測驗', '驗', '考查', '嘗'], [['檢驗', ['test', 'examine', 'inspect'], None, 0.0505711], ['試', ['test', 'try'], None, 0.020115795], ['考', ['test', 'study', 'examine', 'investigate', 'verify', 'check'], None, 0.015184198], ['測驗', ['test', 'put to test'], None, 0.004559123], ['驗', ['test', 'check', 'verify', 'examine', 'prove', 'confirm'], None, 0.0010999396], ['考查', ['test', 'investigate', 'check', 'study'], None, 0.00043074254], ['嘗', ['taste', 'flavor', 'try the flavor', 'test', 'flavour'], None, 6.3755516e-07]], 'test', 2]]

### all-translations Structure Analysis
From what I can tell, the returned list has a bunch of redundant information.
```
["super" categories of the part of speech, for example noun or verbs
    [The list of words],
    [[Each word, a list of translations, an unknown "None", and the frequency]]
    [The input_text]
    [The number of the result]
]
```
### all-translations to list() of dict()
This code pulls out the relevant information.

```
list_of_alternate_translations = list()
for pos_per_translation in result.extra_data['all-translations']:
    part_of_speech_per_translation = pos_per_translation[0]
    for all_translation in pos_per_translation[2]:
        intermediate_dic_for_list = {
                "part-of-speech": part_of_speech_per_translation,
                "all-translation-word": all_translation[0],
                "all-translation-definition": all_translation[1],
                "frequency": all_translation[3], 
            }
            list_of_alternate_translations.append(intermediate_dic_for_list)
print(list_of_alternate_translations)
```

The result is far more usable
```[
	{
		'part-of-speech': 'noun', 
		'all-translation-word': '測試', 
		'all-translation-definition': ['test', 'examination'], 
		'frequency': 0.61608213
	}, 
	{
		'part-of-speech': 'noun', 
		'all-translation-word': '試驗', 
		'all-translation-definition': ['test', 'experiment', 'tentative'], 
		'frequency': 0.21967085
	}, 
	{
		'part-of-speech': 'noun', 
		'all-translation-word': '試', 
		'all-translation-definition': ['test', 'examination', 'experiment', 'exam', 'fitting'], 
		'frequency': 0.020115795
	}, 
	{
		'part-of-speech': 'noun', 
		'all-translation-word': '實驗', 
		'all-translation-definition': ['experiment', 'test'], 
		'frequency': 0.015912903
	}, 
	{
		'part-of-speech': 'noun', 
		'all-translation-word': '考試', 
		'all-translation-definition': ['examination', 'exam', 'test'], 
		'frequency': 0.012588142
	}, 
	{
		'part-of-speech': 'noun', 
		'all-translation-word': '考驗', 
		'all-translation-definition': ['test', 'trial', 'ordeal'], 
		'frequency': 0.012588142
	}, 
	{
		'part-of-speech': 'noun', 
		'all-translation-word': '測驗', 
		'all-translation-definition': ['test', 'quiz'], 
		'frequency': 0.004559123
	}, 
	{
		'part-of-speech': 'verb', 
		'all-translation-word': '檢驗', 
		'all-translation-definition': ['test', 'examine', 'inspect'], 
		'frequency': 0.0505711
	}, 
	{
		'part-of-speech': 'verb', 
		'all-translation-word': '試', 
		'all-translation-definition': ['test', 'try'], 
		'frequency': 0.020115795
	}, 
	{
		'part-of-speech': 'verb', 
		'all-translation-word': '考', 
		'all-translation-definition': ['test', 'study', 'examine', 'investigate', 'verify', 'check'], 
		'frequency': 0.015184198
	}, 
	{
		'part-of-speech': 'verb', 
		'all-translation-word': '測驗', 
		'all-translation-definition': ['test', 'put to test'], 
		'frequency': 0.004559123
	}, 
	{
		'part-of-speech': 'verb', 
		'all-translation-word': '驗', 
		'all-translation-definition': ['test', 'check', 'verify', 'examine', 'prove', 'confirm'], 
		'frequency': 0.0010999396
	}, 
	{
		'part-of-speech': 'verb', 
		'all-translation-word': '考查', 
		'all-translation-definition': ['test', 'investigate', 'check', 'study'], 
		'frequency': 0.00043074254
	}, 
	{
		'part-of-speech': 'verb', 
		'all-translation-word': '嘗', 
		'all-translation-definition': ['taste', 'flavor', 'try the flavor', 'test', 'flavour'], 
		'frequency': 6.3755516e-07
	}
]```

Isn't that nicer?

**Comment by SwedishBarbarossa** [comment]
I made a sampling of results from various languages (always to or from English).
https://github.com/SwedishBarbarossa/translations_test_sample/blob/main/test_sample.py
Test away!
I've tried to solve this problem in a similar way for a personal use-case, and the structure of the response is a bit troublesome.

**Comment by bai-yi-bai** [comment]
Thank you for the star. The sample is not needed.

My code only parses the returned 'all-translations' from the list:
https://github.com/ssut/py-googletrans/blob/d15c94f176463b2ce6199a42a1c517690366977f/googletrans/client.py#L98

My intention was only to provide an example of how much better the output could be. The other 10 items in the list need similar for loops and tests to make sure they are not None:
            0: 'translation',
            1: 'all-translations',
            2: 'original-language',
            5: 'possible-translations',
            6: 'confidence',
            7: 'possible-mistakes',
            8: 'language',
            11: 'synonyms',
            12: 'definitions',
            13: 'examples',
            14: 'see-also'

Unfortunately I don't think I'm the person who can do this because I'm not 100% sure about the structures for those nested lists because the returned data is absent from my test cases/language. I don't have the required meta-linguistic knowledge to accurately guess what all the fields are. It's quite difficult to infer what "None" is.
