### ISSUE TITLE
Worse performance than Google Translation API or translate.google.com

### ISSUE THREAD

**Issue by salvacarrion** [ssut/py-googletrans#333]
I have computed the BLEU score for several test sets obtaining a significantly worse performance (-12.52pts BLEU) than the ones obtained by using the official [Google Translation API](https://github.com/googleapis/python-translate), or by translating a document (Word and Excel) directly with the [website](https://translate.google.com/).

-  **Google Translate**:

| **Method**                  | **BLEU**    |
|--------------------------|---------|
| API (official)           | 42.4157 |
| API (unofficial)         | 29.8926 |
| Web (Word - break lines) | 42.2661 |
| Web (Word - bullets)     | 42.2661 |
| Web (Excel)              | 42.2065 |

> This data corresponds to the `Multi30k/2016` (en-de) testset, downloaded with sacrebleu (no further preprocessing was done). **From english to german**.
> sacrebleu -t multi30k/2016 -l en-de --echo src > multi30k_2016-src.txt
> sacrebleu -t multi30k/2016 -l en-de --echo ref > multi30k_2016-ref.txt

**Others:**
- OS: MacOS
- googletrans version: 4.0.0rc1

**Links:**
[https://translate.google.com/](https://translate.google.com/)
[https://github.com/googleapis/python-translate](https://github.com/googleapis/python-translate)

**Comment by leifadev** [comment]
Thanks for sharing! I am going to scrape the google translate webpage with lxml :p
