### ISSUE TITLE
Bulk translation no longer working.

### ISSUE THREAD

**Issue by blurrred** [ssut/py-googletrans#337]
**Googletrans version:**
- [X] **4.0.0rc1**
- [ ] **3.1.0a0**
- [ ] **3.0.0**
- [ ] **2.x**

**I'm submitting a ...** 

- [X] bug report
- [ ] feature request

**Current behavior:**

Trying to use bulk translation results in an error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "$HOME/.local/lib/python3.10/site-packages/googletrans/client.py", line 219, in translate
    parsed = json.loads(data[0][2])
  File "/usr/lib/python3.10/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType

```

**Expected behavior:**

Normal bulk translation.

**Steps to reproduce:**

Just follow the steps in https://pypi.org/project/googletrans/ for bulk translation. That version no longer works, so I had to install the newer one.

**Comment by blurrred** [comment]
I have tried version 3.1.0a0 and it seems to work fine.

**Comment by fahimito** [comment]
I had the same exact error when using v 4.0.0rc1.

I had to install v 3.1.0a0 instead and the error went away.
