### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by xLinkOut** [ssut/py-googletrans#352]
**Googletrans version:**
- [x] **4.0.0rc1**
- [ ] **3.1.0a0**
- [ ] **3.0.0**
- [ ] **2.x**

**I'm submitting a ...** 
- [x] bug report
- [ ] feature request

**Current behavior:**
TypeError is raised while translating text.

**Expected behavior:**
Translate and return text.

**Steps to reproduce:**
Translate from 'EN' to 'DE' the word 'Dispensers', it raise the TypeError exception.

**Related code:**
```python
output[lang][page_name][key] = translator.translate(value, src='en', dest=lang).text 
```

**Other information:**
```python
Traceback (most recent call last):
File "translate.py", line 95, in <module>
    output[lang][page_name][key] = translator.translate(value, src='en', dest=lang).text 
File "[redacted]/venv/lib/python3.8/site-packages/googletrans/client.py", line 222, in translate
    translated_parts = list(map(lambda part: TranslatedPart(part[0], part[1] if len(part) >= 2 else []), parsed[1][0][0][5]))
TypeError: 'NoneType' object is not iterable
```

**Comment by hp0404** [comment]
see [here](https://github.com/ssut/py-googletrans/issues/260#issuecomment-1189236174)
