### ISSUE TITLE
Cann't use translate() for a list of phrases

### ISSUE THREAD

**Issue by NorzanHusto** [ssut/py-googletrans#357]
**Googletrans version:**
- [ ] **4.0.0rc1**
- [ ] **3.1.0a0**
- [ ] **3.0.0**
- [ ] **2.x**

**I'm submitting a ...** 

- [x] bug report
- [ ] feature request

**Current behavior:**

I'm trying to use translate() for a list of Simplified Chinese phrases, but got "TypeError: the JSON object must be str, bytes or bytearray, not NoneType". It works fine with a single phrase though.

**Expected behavior:**

I assume it should return a list of translated English phrases. 

**Steps to reproduce:**

**Related code:**

```
import googletrans
from googletrans import Translator
translator = Translator()
result = translator.translate(['我', '伸出', '手，', '偷偷', '地', '解开', '了', '我', '的', '安全带。’])
```

**Other information:**

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-94-b7ca66461b7a> in <module>
      3 
      4 # result = translator.translate('我')
----> 5 result = translator.translate(['我', '伸出', '手，', '偷偷', '地', '解开', '了', '我', '的', '安全带。'])
      6 
      7 print(result.src)

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/googletrans/client.py in translate(self, text, dest, src)
    217 
    218         data = json.loads(resp)
--> 219         parsed = json.loads(data[0][2])
    220         # not sure
    221         should_spacing = parsed[1][0][0][3]

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    339     else:
    340         if not isinstance(s, (bytes, bytearray)):
--> 341             raise TypeError(f'the JSON object must be str, bytes or bytearray, '
    342                             f'not {s.__class__.__name__}')
    343         s = s.decode(detect_encoding(s), 'surrogatepass')

TypeError: the JSON object must be str, bytes or bytearray, not NoneType

**Comment by shhossain** [comment]
same here.

**Comment by HIST-VR** [comment]
same

**Comment by SahilNagpure07** [comment]
try this:
`result = translator.translate(str(['我', '伸出', '手，', '偷偷', '地', '解开', '了', '我', '的', '安全带。']))
print(result.text)`
or
`result = translator.translate(('我' '伸出' '手，' '偷偷' '地' '解开' '了' '我' '的' '安全带。'))`
`print(result.text.split(' '))`

**Comment by vovavili** [comment]
Hello, I still experience this issue as of 4.0.0rc1.

**Comment by xHak2215** [comment]
version:4.0.0rc1

```
translator.translate('English text', src='auto', dest='ru').text
```

same error
