### ISSUE TITLE
self.RE_TKK.search(r.text) return None

### ISSUE THREAD

**Issue by mx1234567mx** [ssut/py-googletrans#363]
I get an error:
 
 File "C:\ProjectsPython\googletrans_git\venv\lib\site-packages\googletrans\gtoken.py", line 62, in _update
    code = self.RE_TKK.search(r.text).group(1).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by hoishing** [comment]
use `3.1.0a0` for temp fix, see #280

**Comment by ManuelSchneid3r** [comment]
Hä this one been fixed?
