### ISSUE TITLE
Chinese/Japanese errors causing exceptions

### ISSUE THREAD

**Issue by lucasjfriesen** [ssut/py-googletrans#37]
Attempting to translate strings with either "," or "、" doubled (i.e. ",,", "、、") raises an exception:

```
`translator.translate("I`` need TofeL here ,, they dont know IELTS !! , Smart pepole anyway it is same to study for me . Thank u Omy .")

raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 258 (char 257)
```

I don't know if there is anything you can do about this - I'm getting around it by pre-screening the data and removing the offending sequences.

**Comment by zemicolumn** [comment]
To avoid (i.e. ",,", "、、") , make a conversion function and convert the characters into others.
