### ISSUE TITLE
TypeError: the JSON object must be str, bytes or bytearray, not NoneType

### ISSUE THREAD

**Issue by imrankh46** [ssut/py-googletrans#378]
I am using version 4 , but I got the above error. 
I am using the following code 
```
from googletrans import Translator

# Create a translator object
translator = Translator()

# Open the input file
with open('poems.txt', 'r') as file:
    input_text = file.read()

# Split the input text into smaller chunks (e.g. sentences or paragraphs)
input_chunks = [chunk.strip() for chunk in input_text.split('\n')]

# Translate each chunk
output_chunks = []
for chunk in input_chunks:
    output_chunk = translator.translate(chunk, dest='ur').text
    output_chunks.append(output_chunk)

# Join the output chunks into a single string
output_text = '\n'.join(output_chunks)

# Open the output file
with open('output.txt', 'w') as file:
    file.write(output_text)
```

**Comment by sharmankin** [comment]
I solved this issue with another library (https://github.com/suqingdong/googletranslatepy). I think that this library is dead.

**Comment by sevvvich** [comment]
I have the same error and as I see, responses sometimes are really strange, but not empty at all, there are some strange google codes. And I can't understand what's the principle of getting normal response or just "empty", looks like it's on the Google side, but IDK.

**Comment by imrankh46** [comment]
> I solved this issue with another library (https://github.com/suqingdong/googletranslatepy). I think that this library is dead.

When the token limit exceed, so they give this error.

**Comment by imrankh46** [comment]
> I have the same error and as I see, responses sometimes are really strange, but not empty at all, there are some strange google codes. And I can't understand what's the principle of getting normal response or just "empty", looks like it's on the Google side, but IDK.

When the token limit exceed so they show this type of behavior.

**Comment by imrankh46** [comment]
> I solved this issue with another library (https://github.com/suqingdong/googletranslatepy). I think that this library is dead.

Thanks for suggestion.

**Comment by sevvvich** [comment]
> > I solved this issue with another library (https://github.com/suqingdong/googletranslatepy). I think that this library is dead.
> 
> Thanks for suggestion.

Do you think it's because of library or should we use some tricky ways to avoid token limitations for all free libraries?

**Comment by imrankh46** [comment]
> > > I solved this issue with another library (https://github.com/suqingdong/googletranslatepy). I think that this library is dead.
> > 
> > 
> > Thanks for suggestion.
> 
> Do you think it's because of library or should we use some tricky ways to avoid token limitations for all free libraries?

Yeah it's token limitations issues. I think at a time the library can translate 1500 token or 5000, but when the length are exceed, they showing this error.


Do you think,  the new library also showing this behavior?

**Comment by Knackii** [comment]
rip

**Comment by lionderful** [comment]
pip install googletrans==3.1.0a0
