### ISSUE TITLE
httpx library version dependency issue 

### ISSUE THREAD

**Issue by parkeunsang** [ssut/py-googletrans#380]
**Googletrans version:**
- [x] **4.0.0rc1**
- [ ] **3.1.0a0**
- [ ] **3.0.0**
- [ ] **2.x**

**I'm submitting a ...** 

- [ ] bug report
- [x] feature request

**Current behavior:**

In Python3.9, googletrans library uses 'httpx==0.13.3' version that is too old. So this issue can cause version dependency problems. 
I also recently had this problem related with telegram library and error code =`python-telegram-bot 20.3 requires httpx~=0.24.0, but you have httpx 0.13.3 which is incompatible.`

**Expected behavior:**

httpx version up and  reduce version dependency problems.

**Steps to reproduce:**

Remove legacy code about httpx==0.13.3
**Related code:**

in `client.py` 62line, Remove deprecated typing info 'SyncHTTPTransport'
```
proxies: typing.Dict[str, httpcore.SyncHTTPTransport] = None,
->
proxies = None
```

**Other information:**

**Comment by soniked** [comment]
Thank you for very useful information!
