### ISSUE TITLE
why it raising an error

### ISSUE THREAD

**Issue by balu54** [ssut/py-googletrans#383]
hey i am getting following error how can i fix it

from googletrans import Translator

translator = Translator()
translation = translator.translate('kaise re bhai', dest='en')
print(translation.text)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-3-cb75a510507d>](https://localhost:8080/#) in <cell line: 4>()

----> 4 translation = translator.translate('kaise re bhai', dest='en')

3 frames
[/usr/local/lib/python3.10/dist-packages/googletrans/gtoken.py](https://localhost:8080/#) in _update(self)
     60 
     61         # this will be the same as python code after stripping out a reserved word 'var'
---> 62         code = self.RE_TKK.search(r.text).group(1).replace('var ', '')
     63         # unescape special ascii characters such like a \x3d(=)
     64         code = code.encode().decode('unicode-escape')

AttributeError: 'NoneType' object has no attrib

**Comment by acmpo6ou** [comment]
I'm getting the same error. I can see it has to do with acquiring a token, so I guess their method doesn't work anymore.

**Comment by acmpo6ou** [comment]
Hey, I found the answer: https://github.com/ssut/py-googletrans/issues/366#issuecomment-1613824046
