### ISSUE TITLE
googletrans conflict with python-telegram-bot because of httpx package

### ISSUE THREAD

**Issue by Ammar-Husain** [ssut/py-googletrans#386]
googletrans uses `httpx=0.13.3` which is very old, latest version is `0.25.0`, this lead to confliction with many packages like `python-telegram-bot` which require `httpx~=0.24.1` and many other packages.

can you consider switching to newest versions of `httpx` ?

**Comment by jonbesga** [comment]
Same issue here

**Comment by jahrmando** [comment]
Please update this package version

**Comment by Almas-Ali** [comment]
It's also conflict with openai module just for the outdated httpx module support.


Error statement bellow:
---------------------------------------------
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
openai 1.2.4 requires httpx<1,>=0.23.0, but you have httpx 0.13.3 which is incompatible.

**Comment by nunotexbsd** [comment]
https://github.com/ShivangKakkar/googletrans fork says that makes it possible to use httpx's newer versions than 0.13.3.

It doesn't install script bin/translate so I don't know how this could work.

**Comment by chezihp** [comment]
> Anyone struggling with the httpx error, this might help. Also had to pin it to a specific version. https://github.com/c-goosen/py-googletrans/tree/upgrade-httpx

It doesn't support native bulk translation. Just iterations over it in a loop

**Comment by jhowilbur** [comment]
Resolved here:
https://github.com/ssut/py-googletrans/issues/395
