### ISSUE TITLE
AttributeError: 'None type' object has no attribute 'group'

### ISSUE THREAD

**Issue by heavyweaponsguy11** [ssut/py-googletrans#398]
Here is my code:
`import httpcore
setattr(httpcore, 'SyncHTTPTransport', any)
from googletrans import Translator
import time

languages = ['ar', 'bg', 'hu', 'el', 'da', 'iw', 'ky', 'lo', 'mn', 'de', 'pt', 'ro', 'so', 'tt', 'uz', 'fr', 'hr', 'cs', 'sv', 'et', 'ja']

sentence = input('Enter sentence to translate: ')

translator = Translator()

for lang in languages:
    translated = translator.translate(sentence, dest=lang)
    final_translation = translator.translate(translated.text, src=lang, dest='en')
    print(f'Translate to {final_translation.dest}: {final_translation.text}')`

I wanted to make kind of 'funny translator', which takes a sentence, translates it throught different languages, and then shows the result.
But when I run the programm, I'm recieving that error:
AttributeError: 'None type' object has no attribute 'group'
I tryed to run the programm on 4.0.0rc1 and 3.1.0a0, but it's still doesn't works
How can I fix it? (my Python version: 3.10.5)

**Comment by jackqt** [comment]
same here +1

**Comment by Sungsym** [comment]
> #280
pip install googletrans==3.1.0a0
thanks a lot

**Comment by mercy-git** [comment]
googletrans==3.1.0a0 works when used alone. But it has package dependency error when used along with langchain or llama index. Why is the googletrans latest version so old? What is the alternative or way to fix this?

**Comment by JamieShuai** [comment]
using 4.0.0rc1 version right now, yet still got this problem. seems googletrans need updating
