### ISSUE TITLE
Errors are raised on certain text inputs.

### ISSUE THREAD

**Issue by zwanzika-hatzel** [ssut/py-googletrans#412]
Version:  4.0.0rc1

Code:

from googletrans import Translator
translator = Translator()
translator.translate("child or my", dest="es")

Error:
  File "C:\Users\user\Desktop\venv\Lib\site-packages\googletrans\client.py", line 222, in translate
    translated_parts = list(map(lambda part: TranslatedPart(part[0], part[1] if len(part) >= 2 else []), parsed[1][0][0][5]))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable

**Comment by Itachisann** [comment]
same error with word "finished"
