### ISSUE TITLE
how to translate a web page?

### ISSUE THREAD

**Issue by ruandao** [ssut/py-googletrans#42]
how to translate a web page and get the html response
like this: https://translate.google.com.hk/translate?hl=en&sl=zh-CN&tl=en&u=http://qq.com

**Comment by ssut** [comment]
I close this issue because py-googletrans is just a library that do just do one thing: translating given texts, not translating a web page.

**Comment by milahu** [comment]
see https://github.com/ssut/py-googletrans/issues/99#issuecomment-848714972
