### ISSUE TITLE
Allow a "ignore" feild when translating

### ISSUE THREAD

**Issue by yellowtapes** [ssut/py-googletrans#423]
**Googletrans version:**
- [x] **4.0.0rc1**

**I'm submitting a ...** 

- [ ] bug report
- [x] feature request

**Current behavior:**
When it comes to HTML tags: \<a>, \<strong>, \<em>, special characters: [, ], `, and URLS, googletrans will translate these by seemingly doubling the character/s or removing them breaking formats. Now I can't expect googletrans to look out for these as this issue is specific to me atm, but I'm sure there'd be other cases where individuals have the same issue in different instances. 

I suggest googletrans add a ignore field that accepts a list of items or a Union() to ignore during the translation if possible. eg. `.translate(text = ..., dest = ..., ignore = ...)`

**Expected behavior:**
Ignore specified text and or symbol while translating.

**Related code:**

```py
#eg.1
.translate(text = "I sin went to party, dest = ..., ignore = "sin") 
#result: "I went to party"

#eg.2
.translate(text = "@bobby told `jimmy` [timber] not to go in there!", dest = ..., ignore = ["[", "]", "`", "@"])` 
# result: "bobby told jimmy timber not to go in there!"
```

**Comment by ssut** [comment]
This is not something the googletrans library can handle as this project relies on the Google Translate API. Since this lib is just a wrapper for the API, adding this feature isn't possible.
