### ISSUE TITLE
I just installed the library, but for some reason it is not working.

### ISSUE THREAD

**Issue by gabycperezdias** [ssut/py-googletrans#54]
I am trying the following line in a python console. Any idea?

>>> from googletrans import Translator
>>> translator = Translator()
>>> translator.detect('This sentence is written in English.')
<googletrans.models.Detected object at 0x10ff76518>

**Comment by steremma** [comment]
Try to query the returned object using its attributes. 
For example I had the same issue:
```
>>> from googletrans import Translator
>>> translator = Translator()
>>> translator.translate('Vermoeden van fiscale fraude')
<googletrans.models.Translated at 0x2bb979b70b8>
```

but if I use:
```
>>> from googletrans import Translator
>>> translator = Translator()
>>> translator.translate('Vermoeden van fiscale fraude').text
'Presumption of tax fraud'
```
