### ISSUE TITLE
Implementation of batch translation

### ISSUE THREAD

**Issue by Dobatymo** [ssut/py-googletrans#57]
```python
        if isinstance(text, list):
            result = []
            for item in text:
                translated = self.translate(item, dest=dest, src=src)
                result.append(translated)
        return result
```

As far as I can see, batch processing is implemented here (client.py, `Translator.translate`).
How is this faster than calling `translate()` multiple times from outside the library? If it is not, the documentation should clarify that batch processing is only a convenience function and does not offer any performance benefits.
I would expect batch translation needs a single HTTP round-trip, but if I understand the code correctly, this is not the case.

**Comment by kngxscn** [comment]
I agree with you. The bulk mode does multiple translations in one session, not in one request, so it can't improve the speed. You may put multiple translations in one request by splitting the text with '\n'. By this way the program can be faster but sometimes I encounter the error describe in #91
