### ISSUE TITLE
After some time ValueError("No JSON object could be decoded")

### ISSUE THREAD

**Issue by Andy671** [ssut/py-googletrans#67]
I've used this library for a few days. 
But yesterday it had broken. 

I got _After some time ValueError("No JSON object could be decoded")_

after calling

`translator.translate('word', dest = 'ru')`

If I use `'translate.google.co.kr'` everything works.

How to fix that? I need a lot of translations to be done. Do I need proxies?

**Comment by crazyfrogspb** [comment]
It probably means that your IP has been banned by Google. Try looking at the content of the generated JSON, and use timeouts between calls in the future.

**Comment by Andy671** [comment]
@crazyfrogspb , thanks for the reply. I got it. 
I am translating batches of strings. Is it better to translate everything with bulk function(via single http session) or with multiple http sessions? I mean, does it matter to google how many requests I make via single http session?

**Comment by Paethon** [comment]
Thanks. I also had this issue after some time (I am using the batch-function)
But at least for me, restarting the Python session and trying it maybe 20sec later it worked again. So who knows ...

**Comment by FireFlashing** [comment]
Does anyone know how long it takes before your ip gets unbanned, if it does?
