### ISSUE TITLE
Error Message: size = len(text) TypeError: object of type 'float' has no len()

### ISSUE THREAD

**Issue by Martinhasnoclue** [ssut/py-googletrans#70]
Hi,

I don't have a clue what I'm doing/doing wrong, but I have the following script. What should it do:
-Open an excel sheet
-choose the desired values and put them in a list
-choose source and destination language
-translate

Here the code:

[<script src="https://gist.github.com/Martinhasnoclue/a2cf9c785236c20d07f7ce3ce5433763.js"></script>
](url)

The error message:

Traceback (most recent call last):
  File "Translator.py", line 45, in <module>
    translations = translator.translate(data, dest = dest_lan, src = source_lan)

  File "C:\Users\fzdb7b\Python\lib\site-packages\googletrans\client.py", line 167, in translate
    translated = self.translate(item, dest=dest, src=src)
  File "C:\Users\fzdb7b\Python\lib\site-packages\googletrans\client.py", line 172, in translate
    data = self._translate(text, dest, src)
  File "C:\Users\fzdb7b\Python\lib\site-packages\googletrans\client.py", line 75, in _translate
    token = self.token_acquirer.do(text)
  File "C:\Users\fzdb7b\Python\lib\site-packages\googletrans\gtoken.py", line 181, in do
    tk = self.acquire(text)
  File "C:\Users\fzdb7b\Python\lib\site-packages\googletrans\gtoken.py", line 145, in acquire
    size = len(text)
TypeError: object of type 'float' has no len()

Error happens every time. Using python 3.6.1. Works fine if I put random words in

`
data=["chien", "bon jour"]
`
 The worksheet has a lot of rows (> 2500). It seems that there is a problem with the content. In column 7 there is text like: "ABC_DEF_GHI" and in column 19 is text like: "0x00: ABC_DEF \n0x01: GHI_KLM.

Perhaps somebody can help.
Thx

**Comment by Martinhasnoclue** [comment]
#-------------------------------------------------------------------------
#Copy Excel file----------------------------------------------------------
#-------------------------------------------------------------------------
 
wb1 = load_workbook("Input_document.xlsx")
ws1=wb1.active

data=[]

for row in ws1.iter_rows():
    for cell in row:
        if cell.value==None:  #if value == None, translation is not possible
            cell.value="x"
    data.append(row[7].value)  #Only column 7 and 19 are important to translate
    data.append(row[19].value)

#-----------------------------------------------------------------------------
#Translation
#-----------------------------------------------------------------------------

print("Insert destination language: For english: en, for german: de, for french: fr") #choose destination language
dest_lan = input()
print("Insert source language: For french: fr, english: en, for german: de") #choose source language
source_lan = input()

translator = Translator()
translations = translator.translate(data, dest = dest_lan, src = source_lan)

**Comment by markolofsen** [comment]
Fixed library are here [https://pypi.org/project/py-translator/](https://pypi.org/project/py-translator/)
