### ISSUE TITLE
VPS with SSL certificate: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by joshbindels** [ssut/py-googletrans#71]
When I try to translate on my VPS which has SSL/HTTPS I get this error: 'NoneType' object has no attribute 'group'

But when I run on localhost there is no problem

**Comment by MaximusPX** [comment]
@joshbindels Hey, how did you manage to fix this problem?

**Comment by joshbindels** [comment]
@MaximusPX it turns out that it was just an issue of making too many requests. So I just throttled my application to make a max of 2 requests/second and it's working fine.
