### ISSUE TITLE
When detecting text it returns a language not in the list.

### ISSUE THREAD

**Issue by HexCodeFFF** [ssut/py-googletrans#72]
I implemented this API in a discord bot (very nice API, it works well), and I was trying to translate some turkish text "Oh deme püf de!" that someone sent.
When i set it to detect the language, it sent an error and I figured out it thought the language was "trro" when it was Turkish.
This is not in googletrans.LANGUAGES nor does it make sense since the actual google translate detects it as Turkish.

**Comment by Hexbugman213** [comment]
It interprets other turkish text just fine BTW
