### ISSUE TITLE
Using bulk requests causes google to block you

### ISSUE THREAD

**Issue by gorm-db** [ssut/py-googletrans#76]
Not sure how many times it takes to trigger, maybe around 40 or 50 translations. The phrases must be different or it will not cause the block probably because the results were cached.
```
import googletrans
translator = googletrans.Translator()
translator.translate(['foo', 'bar'])
```

Result: 

<b>About this page</b><br><br>Our systems have detected unusual traffic from your computer network.  This page checks to see if it&#39;s really you sending the requests, and not a robot.  <a href="#" onclick="document.getElementById('infoDiv').style.display='block';">Why did this happen?</a><br><br>
<div id="infoDiv" style="display:none; background-color:#eee; padding:10px; margin:0 0 15px 0; line-height:1.4em;">
This page appears when Google automatically detects requests coming from your computer network which appear to be in violation of the <a href="//www.google.com/policies/terms/">Terms of Service</a>. The block will expire shortly after those requests stop.  In the meantime, solving the above CAPTCHA will let you continue to use our services.<br><br>This traffic may have been sent by malicious software, a browser plug-in, or a script that sends automated requests.  If you share your network connection, ask your administrator for help &mdash; a different computer using the same IP address may be responsible.  <a href="//support.google.com/websearch/answer/86640">Learn more</a><br><br>Sometimes you may be asked to solve the CAPTCHA if you are using advanced terms that robots are known to use, or sending requests very quickly.
</div>

**Comment by iamanam** [comment]
found any solution?

**Comment by Vide459** [comment]
Hi,
Can you suggest how can we use proxies. 
If the google has blocked us after the large number of requests, can we change our proxy and continue with the remaining translations. I'm new to python. Can anyone explain in detail.

**Comment by mzaidi59** [comment]
Querying too often prompts the API to block your IP.
Proxies do not seem to work, changing your wifi connections does help.

A better solution is to use adequate delays to avoid being classified as a malicious user. I kept on playing with delays, delay after a pair of translations(2 secs) and delay after each group of 10 translations(15 secs). It gets slow, but is faster and better than waiting to be unblocked.

**Comment by interlark** [comment]
Indeed, proxy in this case don't work.

**Comment by interlark** [comment]
Indeed, proxies in this case don't work.
