### ISSUE TITLE
gtoken changed

### ISSUE THREAD

**Issue by gorm-db** [ssut/py-googletrans#77]
The gtoken format has changed. This doesn't work anymore.

**Comment by ebs111** [comment]
solved it 
here is the solution
![image](https://user-images.githubusercontent.com/26479053/45846857-b3a85200-bd31-11e8-8354-7c7fa8f64e07.png)

**Comment by Dobatymo** [comment]
Thanks, I had the same problem.

**Comment by dobilquoo** [comment]
+1.

Is this on PyPi?

**Comment by ebs111** [comment]
its in gtoken.py

**Comment by programmerchad** [comment]
After applying @ebs111's fix, I started getting other errors and noticed it was due to me receiving a 403 error code.  Comparing the token generated by gtoken.py against a token generated from visiting their site, they look different.

gtoken:     684737.684737
site token: 649320.1010751

**Comment by iamanam** [comment]
Seems like it works for sometime and after sometime get blocked by google, showing 403 error code. Do they set up rate limiting or it's just about the token?

**Comment by pendave** [comment]
> Seems like it works for sometime and after sometime get blocked by google, showing 403 error code. Do they set up rate limiting or it's just about the token?

Me too here, and I have to change to proxy and it works again.

**Comment by iamanam** [comment]
how do you do that @pendave ? can you share?

**Comment by joaonetto** [comment]
Thanks @ebs111 . Working fine.

**Comment by markolofsen** [comment]
Can somebody update this repo?

**Comment by markolofsen** [comment]
@ebs111 it doesn't work
```
    def _update(self):
        """update tkk
        """

        # we don't need to update the base TKK value when it is still valid
        r = self.session.get(self.host)
        self.tkk = self.RE_TKK.findall(r.text)[0]

        now = math.floor(int(time.time() * 1000) / 3600000.0)
        if self.tkk and int(self.tkk.split('.')[0]) == now:
            return
        
        # this will be the same as python code after stripping out a reserved word 'var'
        code = unicode(self.RE_TKK.search(r.text).group(1)).replace('var ', '')
        # unescape special ascii characters such like a \x3d(=)
        if PY3:  # pragma: no cover
            code = code.encode().decode('unicode-escape')
        else:  # pragma: no cover
            code = code.decode('string_escape')
```

**Comment by duarteocarmo** [comment]
@markolofsen you’re missing the line before __init__ ?

**Comment by duarteocarmo** [comment]
@markolofsen try my file here (https://pastebin.com/V4YFtct5) replace it in your library file. If it's still not working just send the error.

**Comment by markolofsen** [comment]
Fixed library are here [https://pypi.org/project/py-translator/](https://pypi.org/project/py-translator/)

**Comment by berkayberkman** [comment]
> @markolofsen try my file here (https://pastebin.com/V4YFtct5) replace it in your library file. If it's still not working just send the error.

can you please send the file or  share code snippet again? I have same problem and cant fix. Also I am working on python 3.6 and py-translator support 3.4 :(
