### ISSUE TITLE
how to connect to a proxy?

### ISSUE THREAD

**Issue by i4mShayan** [ssut/py-googletrans#79]
hey guys !
this is my code to connect to my socks5 proxy:
`    translator = Translator(proxies={'socks5': '{}:{}@{}:{}'.format(user_name,password,ip,port )})`

is it correct?
because it **didn't work** :(

tnx !

**Comment by markolofsen** [comment]
Fixed library are here [https://pypi.org/project/py-translator/](https://pypi.org/project/py-translator/)
