### ISSUE TITLE
Doesn't Seem to be Working on Windows 10

### ISSUE THREAD

**Issue by Suleman-Elahi** [ssut/py-googletrans#84]
On Windows 10, The command line tool wasn't able to translate text.

![image](https://user-images.githubusercontent.com/24384996/46200772-23b96800-c330-11e8-9517-f3f8665a2e18.png)

The interpreter is not working too I guess.

![image](https://user-images.githubusercontent.com/24384996/46200868-62e7b900-c330-11e8-8159-0caa35cf5501.png)

**Comment by NawtJ0sh** [comment]
https://github.com/ssut/py-googletrans/pull/78

**Comment by NawtJ0sh** [comment]
Hi, all you gotta do is edit this into the gtoken.py file

    RE_TKK = re.compile(r'TKK=eval\(\'\(\(function\(\)\{(.+?)\}\)\(\)\)\'\);',
                        re.DOTALL)
    RE_RAWTKK = re.compile(r'TKK=\'([^\']*)\';',re.DOTALL)

    def __init__(self, tkk='0', session=None, host='translate.google.com'):
        self.session = session or requests.Session()
        self.tkk = tkk
        self.host = host if 'http' in host else 'https://' + host

    def _update(self):
        """update tkk
        """
        # we don't need to update the base TKK value when it is still valid
        now = math.floor(int(time.time() * 1000) / 3600000.0)
        if self.tkk and int(self.tkk.split('.')[0]) == now:
            return

        r = self.session.get(self.host)

        rawtkk = self.RE_RAWTKK.search(r.text)
        if rawtkk:
            self.tkk = rawtkk.group(1)
            return

**Comment by kngxscn** [comment]
> Hi, all you gotta do is edit this into the gtoken.py file
> 
> ```
> RE_TKK = re.compile(r'TKK=eval\(\'\(\(function\(\)\{(.+?)\}\)\(\)\)\'\);',
>                     re.DOTALL)
> RE_RAWTKK = re.compile(r'TKK=\'([^\']*)\';',re.DOTALL)
> 
> def __init__(self, tkk='0', session=None, host='translate.google.com'):
>     self.session = session or requests.Session()
>     self.tkk = tkk
>     self.host = host if 'http' in host else 'https://' + host
> 
> def _update(self):
>     """update tkk
>     """
>     # we don't need to update the base TKK value when it is still valid
>     now = math.floor(int(time.time() * 1000) / 3600000.0)
>     if self.tkk and int(self.tkk.split('.')[0]) == now:
>         return
> 
>     r = self.session.get(self.host)
> 
>     rawtkk = self.RE_RAWTKK.search(r.text)
>     if rawtkk:
>         self.tkk = rawtkk.group(1)
>         return
> ```

This helps me so much!

**Comment by dripti** [comment]
hey i did the same. However, now i am getting the json decode error. Anything on that?

**Comment by NawtJ0sh** [comment]
Nah i don't think there is a fix for that yet.

**Comment by dripti** [comment]
so it keeps happening? no alternative?
