### ISSUE TITLE
I find  google  has blocked ip very quickly recently 

### ISSUE THREAD

**Issue by godkillok** [ssut/py-googletrans#85]
my code sleep 1s after 5 visits, but it still blocks me  after only a few minutes later. any  solution?

**Comment by foyamoon** [comment]
For how long is your ip blocked? Do you have to solve captcha to remove the ban?

**Comment by markolofsen** [comment]
Fixed library are here [https://pypi.org/project/py-translator/](https://pypi.org/project/py-translator/)
