### ISSUE TITLE
zh-tw and zh-cn confused

### ISSUE THREAD

**Issue by Isaac-the-Man** [ssut/py-googletrans#87]
I notice that the `Translator.detect()` function always returns "zh-CN" (which is simplified Chinese) and even when I pass in traditional Chinese characters. By the way, I'm a native speaker of both Chinese so I am pretty confident with this error.

Sample traditional Chinese Input:
![image](https://user-images.githubusercontent.com/29915393/46567950-a74a0900-c96f-11e8-8046-b972ccefa152.png)

Sample simplified Chinese Input:
![image](https://user-images.githubusercontent.com/29915393/46567956-ce083f80-c96f-11e8-938a-14d789dd3efb.png)

**Comment by markolofsen** [comment]
Fixed library are here [https://pypi.org/project/py-translator/](https://pypi.org/project/py-translator/)
