### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by UziFTW** [ssut/py-googletrans#88]
I have tried reinstalling googletrans but it hasn't seemed to work. Maybe you can help?
Here is the code:

`from googletrans import Translator`
`translator=Translator()`
`print(translator.translate('Hola.', dest='fr').text)`

Here is the error:
>Traceback (most recent call last):
  File "C:\Users\user\desktop\folder\translate.py", line 3, in <module>
    print(translator.translate('Hola.', dest='fr'))
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\googletrans\client.py", line 172, in translate
    data = self._translate(text, dest, src)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\googletrans\client.py", line 75, in _translate
    token = self.token_acquirer.do(text)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\googletrans\gtoken.py", line 180, in do
    self._update()
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\googletrans\gtoken.py", line 59, in _update
    code = unicode(self.RE_TKK.search(r.text).group(1)).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by durakkerem** [comment]
Please refer to here for a temporary fix: https://stackoverflow.com/a/52487148/2231702

**Comment by markolofsen** [comment]
Fixed library are here [https://pypi.org/project/py-translator/](https://pypi.org/project/py-translator/)

**Comment by 1049451037** [comment]
> Fixed library are here https://pypi.org/project/py-translator/

not working for me...

**Comment by berkayalan** [comment]
> Fixed library are here https://pypi.org/project/py-translator/

The page doesn't work actually.

**Comment by Liguo-Ma** [comment]
Hello
I get 'NoneType' object has no attribute 'group'
I have tried this
$ pip uninstall googletrans
$ git clone https://github.com/BoseCorp/py-googletrans.git
$ cd ./py-googletrans
$ python setup.py install
But get same issue
Please help me

**Comment by TalibCode** [comment]
> Hello
> I get 'NoneType' object has no attribute 'group'
> I have tried this
> $ pip uninstall googletrans
> $ git clone https://github.com/BoseCorp/py-googletrans.git
> $ cd ./py-googletrans
> $ python setup.py install
> But get same issue
> Please help me

I tried the same way and got the same error again, I stopped the thread by time.sleep() before resending the next translate request, it worked for me.
