### ISSUE TITLE
JSONDecodeError may be caused by more than 3000 chars

### ISSUE THREAD

**Issue by kngxscn** [ssut/py-googletrans#91]
If I put more than 3000 chars in a request, it will raise a JSONDecodeError. Do anyone know how to solve it?

**Comment by Colanim** [comment]
Did you try [this](https://stackoverflow.com/questions/52455774/googletrans-stopped-working-with-error-nonetype-object-has-no-attribute-group/52456197#52456197) ?

**Comment by kngxscn** [comment]
> Did you try [this](https://stackoverflow.com/questions/52455774/googletrans-stopped-working-with-error-nonetype-object-has-no-attribute-group/52456197#52456197) ?

I know the link you mentioned and I have already used the fork. But my problem is not related to this. I think it is just related to the amount of chars.

**Comment by kngxscn** [comment]
By the way, Google's limit is 5000 chars

**Comment by kngxscn** [comment]
I have known why. The method len() in Python3 return the amount of words, not the chars(bytes) of words. I should use len(sometext.encode('utf-8')) to compare with the 5000 chars limit of Google Translate.
![1541070390421](https://user-images.githubusercontent.com/4049156/47849315-151d0f80-de0c-11e8-859d-9aeb02fa69c4.jpg)
