### ISSUE TITLE
[Error] Google changed their API... again

### ISSUE THREAD

**Issue by Darkblader24** [ssut/py-googletrans#93]
Google has changed their API yet again. 
Using this tool and the fix in #78 no longer works as it now gives this error:

`\googletrans\gtoken.py", line 66, in _update
    code = unicode(self.RE_TKK.search(r.text).group(1)).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'`

Does anybody have an idea how to fix this?

**Comment by elliottzheng** [comment]
I met the same error，any solution？

**Comment by guiguihao** [comment]
I met the same error

**Comment by karenwang38** [comment]
I met the same error, too.

**Comment by elliottzheng** [comment]
@liling198658 thanks，it worked.

**Comment by hnljq** [comment]
this is a python3 code wrote in year 2014.but it worked , why ?

import urllib.request
import sys
typ = sys.getfilesystemencoding()
def translate(querystr, to_l="zh", from_l="en"):
    '''for google tranlate by doom
    '''
    C_agent = {'User-Agent': "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.165063 Safari/537.36 AppEngine-Google."}
    flag = 'class="t0">'
    tarurl = "http://translate.google.cn/m?hl=%s&sl=%s&q=%s" % (to_l, from_l, querystr.replace(" ", "+"))
    request = urllib.request.Request(tarurl, headers=C_agent)
    page = str(urllib.request.urlopen(request).read().decode(typ))
    target = page[page.find(flag) + len(flag):]
    target = target.split("<")[0]
    return target
print(translate('hello'))

**Comment by kalutika** [comment]
> My husband got mine to work by doing this to gtoken.py:
> 
> Change
> 
> ```
> RE_TKK = re.compile(r'TKK=eval\(\'\(\(function\(\)\{(.+?)\}\)\(\)\)\'\);',
>                         re.DOTALL)
> RE_RAWTKK = re.compile(r'TKK=\'([^\']*)\';', re.DOTALL)
> ```
> to
> 
> ```
> RE_TKK = re.compile(r'tkk:\'(.+?)\'', re.DOTALL)
> RE_RAWTKK = re.compile(r'tkk:\'(.+?)\'', re.DOTALL)
> ```
> Though he isn't really sure of the differences between RAWTKK and TKK, but this was just a really quick fix that he implemented.

After fixing it, I got this error:
self.tkk = self.RE_TKK.findall(r.text)[0]
IndexError: list index out of range

**Comment by yoyonel** [comment]
@liling198658 Where are you find the definition/setting of `RE_RAWTKK` please ?
By the way, this fix on `RE_TKK` (setting) not working for me, the error is different after but still an error (403 error) :p
Can you send me your (google) token generated with string/text = "Hello" please ?

**Comment by yasirtug** [comment]
@hnljq this code is not using the api, downloads the whole result page and extracts the translated text from it. i suppose this method will work when everything fails but it shouldn't be the first thing to apply, it will consume more bandwidth and process power.

**Comment by hnljq** [comment]
> @hnljq this code is not using the api, downloads the whole result page and extracts the translated text from it. i suppose this method will work when everything fails but it shouldn't be the first thing to apply, it will consume more bandwidth and process power.

 google change its api so frequently, so many python packages didn't work . do you know the differences between the code and googletrans package about how to get the translation result?

**Comment by yoyonel** [comment]
Using advices/comments from yasirtug and the code of hnljq,
a notebook using lorem (french -> english) and with non-ascii chars => [](https://gist.github.com/yoyonel/78081a1466121617ff27c307a79b82cd#file-google_translate-ipynb)

**Comment by jaysama** [comment]
Still doesn't work for me...

`File "build\bdist.win32\egg\googletrans\gtoken.py", line 66, in _update
AttributeError: 'NoneType' object has no attribute 'group'`

**Comment by yoyonel** [comment]
@jaysama  Yep, and if you debug (step by step) you will see  a return result with a 404 error. I think the gtoken is not valid (anymore) so we can't ask for a (google) translation service.

**Comment by Guy-Dipietro-Bose** [comment]
Updated https://github.com/ssut/py-googletrans/pull/78 with fix from @liling198658

**Comment by yoyonel** [comment]
@Guy-Dipietro-Bose  you're my hero ! :D
Unit tests work fine now ! Thx again !

**Comment by yoyonel** [comment]
> This page appears when Google automatically detects requests coming from your computer network which appear to be in violation of the <a href="//www.google.com/policies/terms/">Terms of Service</a>. The block will expire shortly after those requests stop.<br><br>This traffic may have been sent by malicious software, a browser plug-in, or a script that sends automated requests.  If you share your network connection, ask your administrator for help &mdash; a different computer using the same IP address may be responsible.

oupppssss :p

**Comment by 1453055** [comment]
> My husband got mine to work by doing this to gtoken.py:
> 
> Change
> 
> ```
> RE_TKK = re.compile(r'TKK=eval\(\'\(\(function\(\)\{(.+?)\}\)\(\)\)\'\);',
>                         re.DOTALL)
> RE_RAWTKK = re.compile(r'TKK=\'([^\']*)\';', re.DOTALL)
> ```
> to
> 
> ```
> RE_TKK = re.compile(r'tkk:\'(.+?)\'', re.DOTALL)
> RE_RAWTKK = re.compile(r'tkk:\'(.+?)\'', re.DOTALL)
> ```
> Though he isn't really sure of the differences between RAWTKK and TKK, but this was just a really quick fix that he implemented.

thanks, it works for me

**Comment by hnljq** [comment]
> @hnljq couldn't know what kind of answer do you exactly want and i will repeat a little, sorry for that.
> with this method, we get the result by using google's own way, which is to ask with a secret token and get the result with some extra details like 'confidence' directly.
> with your code, we literally download [this page](https://translate.google.com/m?hl=zh&sl=en&q=hello) to translate 'hello' to chinese from english, and then parse the downloaded page to take the result ' 你好 '.
> out of topic but i just realised that your code is also not enough to work with queries which include non ascii characters. this can be solved though, by using percent-encoding.

could u please teach me how to use percent-encoding ? it's right?
page = str(urllib.request.urlopen(request).read().decode('utf-8'))
as you see, I am a python beginner. thanks

**Comment by yasirtug** [comment]
@hnljq
you can check @yoyonel's [code](https://github.com/ssut/py-googletrans/issues/93#issuecomment-442849316), it uses percent-encoding by using [urlling.parse.quote()](https://docs.python.org/3.2/library/urllib.parse.html#url-quoting) function.

>page = str(urllib.request.urlopen(request).read().decode('utf-8'))

i am not sure about what this decode function does but it is not doing anything on the url part, so this is not helpful about non-ascii chars. you can check the wikipedia page for detailed information about percent-encoding.

you're welcome, i am not an expert too.

**Comment by BeCuriousCat** [comment]
Does anyone can help me? I had reinstall `py-googletrans`
While i replace the 
```
RE_TKK = re.compile(r'TKK=eval\(\'\(\(function\(\)\{(.+?)\}\)\(\)\)\'\);',
                        re.DOTALL)
RE_RAWTKK = re.compile(r'TKK=\'([^\']*)\';', re.DOTALL)

```
with 
```
RE_TKK = re.compile(r'tkk:\'(.+?)\'', re.DOTALL)
RE_RAWTKK = re.compile(r'tkk:\'(.+?)\'', re.DOTALL)
```

it's still can't work. Actually i just found the 
```
RE_TKK = re.compile(r'TKK=eval\(\'\(\(function\(\)\{(.+?)\}\)\(\)\)\'\);',
                        re.DOTALL)
```

not found `RE_RAWTKK`

There is my code and error information:
```
from googletrans import Translator
print(Translator(service_urls=['translate.google.cn']).translate('音乐',dest='en'))
```

```---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-17-4a96c96b0f66> in <module>()
      1 from googletrans import Translator
----> 2 print(Translator(service_urls=['translate.google.cn']).translate('音乐',dest='en'))

~/anaconda3/lib/python3.6/site-packages/googletrans/client.py in translate(self, text, dest, src)
    170 
    171         origin = text
--> 172         data = self._translate(text, dest, src)
    173 
    174         # this code will be updated when the format is changed.

~/anaconda3/lib/python3.6/site-packages/googletrans/client.py in _translate(self, text, dest, src)
     73             text = text.decode('utf-8')
     74 
---> 75         token = self.token_acquirer.do(text)
     76         params = utils.build_params(query=text, src=src, dest=dest,
     77                                     token=token)

~/anaconda3/lib/python3.6/site-packages/googletrans/gtoken.py in do(self, text)
    182         self._update()
    183         tk = self.acquire(text)
--> 184         return tk

~/anaconda3/lib/python3.6/site-packages/googletrans/gtoken.py in _update(self)
     54         # we don't need to update the base TKK value when it is still valid
     55         now = math.floor(int(time.time() * 1000) / 3600000.0)
---> 56         if self.tkk and int(self.tkk.split('.')[0]) == now:
     57             return
     58 

IndexError: list index out of range
```

**Comment by elzeard91** [comment]
use this one
https://github.com/ssut/py-googletrans/blob/8940fb67f9178aad535b786b2af411e78c5f83c7/googletrans/gtoken.py

**Comment by hnljq** [comment]
> # Ok. i solve it with copy someone's gtoken.py...
> there is his repository..Thank you for ur code....
> https://github.com/BoseCorp/py-googletrans/blob/master/googletrans/gtoken.py
> Does anyone can help me? I had reinstall `py-googletrans`
> While i replace the
> 
> ```
> RE_TKK = re.compile(r'TKK=eval\(\'\(\(function\(\)\{(.+?)\}\)\(\)\)\'\);',
>                         re.DOTALL)
> RE_RAWTKK = re.compile(r'TKK=\'([^\']*)\';', re.DOTALL)
> ```
> with
> 
> ```
> RE_TKK = re.compile(r'tkk:\'(.+?)\'', re.DOTALL)
> RE_RAWTKK = re.compile(r'tkk:\'(.+?)\'', re.DOTALL)
> ```
> it's still can't work. Actually i just found the
> 
> ```
> RE_TKK = re.compile(r'TKK=eval\(\'\(\(function\(\)\{(.+?)\}\)\(\)\)\'\);',
>                         re.DOTALL)
> ```
> not found `RE_RAWTKK`
> 
> There is my code and error information:
> 
> ```
> from googletrans import Translator
> print(Translator(service_urls=['translate.google.cn']).translate('音乐',dest='en'))
> ```
> ```
> IndexError                                Traceback (most recent call last)
> <ipython-input-17-4a96c96b0f66> in <module>()
>       1 from googletrans import Translator
> ----> 2 print(Translator(service_urls=['translate.google.cn']).translate('音乐',dest='en'))
> 
> ~/anaconda3/lib/python3.6/site-packages/googletrans/client.py in translate(self, text, dest, src)
>     170 
>     171         origin = text
> --> 172         data = self._translate(text, dest, src)
>     173 
>     174         # this code will be updated when the format is changed.
> 
> ~/anaconda3/lib/python3.6/site-packages/googletrans/client.py in _translate(self, text, dest, src)
>      73             text = text.decode('utf-8')
>      74 
> ---> 75         token = self.token_acquirer.do(text)
>      76         params = utils.build_params(query=text, src=src, dest=dest,
>      77                                     token=token)
> 
> ~/anaconda3/lib/python3.6/site-packages/googletrans/gtoken.py in do(self, text)
>     182         self._update()
>     183         tk = self.acquire(text)
> --> 184         return tk
> 
> ~/anaconda3/lib/python3.6/site-packages/googletrans/gtoken.py in _update(self)
>      54         # we don't need to update the base TKK value when it is still valid
>      55         now = math.floor(int(time.time() * 1000) / 3600000.0)
> ---> 56         if self.tkk and int(self.tkk.split('.')[0]) == now:
>      57             return
>      58 
> 
> IndexError: list index out of range
> ```

you are not only one
