### ISSUE TITLE
Blocking issue with bulk mode

### ISSUE THREAD

**Issue by Vide459** [ssut/py-googletrans#98]
Hi I am trying to translate bulk data using an automated script. But google is banning my ip after few requests. Is there any way to make bulk translation successful. I'm new to python. Can anyone help me with any solution.

**Comment by elieobeid7** [comment]
Try using a proxy, divide that big bulk request into smaller requests and put like 10s delay between each request

**Comment by pendave** [comment]
Yes, directly connect to the Google translation service is very easily to be banned. So I use several proxies to choose with command lines.
![s flo pgejd1w3qci wvl](https://user-images.githubusercontent.com/1331881/50977491-609b1a80-152d-11e9-872a-c75990daa3cc.png)
