### ISSUE TITLE
HTML format not supported

### ISSUE THREAD

**Issue by sep1** [ssut/py-googletrans#99]
How can i translate html using this library? If it is not possible, how do i filter all html tags and keep all html tags in the traslated version?

**Comment by elzeard91** [comment]
Try web scraping 
https://towardsdatascience.com/data-science-skills-web-scraping-using-python-d1a85ef607ed

**Comment by milahu** [comment]
wontfix, eh?

i solved this with my html2google encoder in my [translate.js](https://github.com/milahu/alchi/blob/master/src/alchi-book/scripts/translate.js) script
to get character-exact html translations with google's free API

also see my post in [Prohibit the translation of pieces of text in Google Translate](https://webapps.stackexchange.com/a/154694/273346)
